//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.TeamFoundation.Migration.Toolkit.ServerDiff {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ServerDiffResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServerDiffResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.TeamFoundation.Migration.Toolkit.ServerDiff.ServerDiffResources", typeof(ServerDiffResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All contents match!.
        /// </summary>
        internal static string AllContentsMatch {
            get {
                return ResourceManager.GetString("AllContentsMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The contents do not match.  The migration may have had errors..
        /// </summary>
        internal static string ContentsDoNotMatch {
            get {
                return ResourceManager.GetString("ContentsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred running ServerDiff: {0}.
        /// </summary>
        internal static string ExceptionRunningServerDiff {
            get {
                return ResourceManager.GetString("ExceptionRunningServerDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Exception occurred trying to store ServerDiff results in the TFS_IntegrationPlatform Database: {0}.
        /// </summary>
        internal static string ExceptionStoringResultsInDB {
            get {
                return ResourceManager.GetString("ExceptionStoringResultsInDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files match. Source: {0} Target: {1}.
        /// </summary>
        internal static string FilesMatch {
            get {
                return ResourceManager.GetString("FilesMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid XML document returned in by the adapter for &apos;{0}&apos; in its IDiffItem implementation.
        /// </summary>
        internal static string InvalidXMLDocumentForDiffItem {
            get {
                return ResourceManager.GetString("InvalidXMLDocumentForDiffItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item exists on both systems but content doesn&apos;t match: {0}.
        /// </summary>
        internal static string ItemContentDoesNotMatch {
            get {
                return ResourceManager.GetString("ItemContentDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item only exists on source system: {0}.
        /// </summary>
        internal static string ItemOnlyFoundOnSource {
            get {
                return ResourceManager.GetString("ItemOnlyFoundOnSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item only exists on target system: {0}.
        /// </summary>
        internal static string ItemOnlyFoundOnTarget {
            get {
                return ResourceManager.GetString("ItemOnlyFoundOnTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration source system: {0}.
        /// </summary>
        internal static string MigrationSourceName {
            get {
                return ResourceManager.GetString("MigrationSourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration target system: {0}.
        /// </summary>
        internal static string MigrationTargetName {
            get {
                return ResourceManager.GetString("MigrationTargetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active session of type {0} was found.
        /// </summary>
        internal static string NoActiveSessionsWithTypeFound {
            get {
                return ResourceManager.GetString("NoActiveSessionsWithTypeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing source folder: {0}.
        /// </summary>
        internal static string ProcessingSourceFolder {
            get {
                return ResourceManager.GetString("ProcessingSourceFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provider &apos;{0}&apos; does not implement the interface IServerPathTranslationService so a diff operation cannot be performed..
        /// </summary>
        internal static string ProviderDoesNotImplementServerPathTranslationInterface {
            get {
                return ResourceManager.GetString("ProviderDoesNotImplementServerPathTranslationInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provider &apos;{0}&apos; does not implement the interface IVCServerDiffProvider so a diff operation cannot be performed..
        /// </summary>
        internal static string ProviderDoesNotImplementVCDiffInterface {
            get {
                return ResourceManager.GetString("ProviderDoesNotImplementVCDiffInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provider &apos;{0}&apos; does not implement the interface IWITDiffProvider so a diff operation cannot be performed..
        /// </summary>
        internal static string ProviderDoesNotImplementWITDiffInterface {
            get {
                return ResourceManager.GetString("ProviderDoesNotImplementWITDiffInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServerDiff: ERROR: {0}.
        /// </summary>
        internal static string ServerDiffError {
            get {
                return ResourceManager.GetString("ServerDiffError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServerDiff: INFO: {0}.
        /// </summary>
        internal static string ServerDiffInfo {
            get {
                return ResourceManager.GetString("ServerDiffInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} woke up and is looking for active {1} sessions.
        /// </summary>
        internal static string ServerDiffJobRunning {
            get {
                return ResourceManager.GetString("ServerDiffJobRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} sleeping.
        /// </summary>
        internal static string ServerDiffJobSleeping {
            get {
                return ResourceManager.GetString("ServerDiffJobSleeping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no provider loaded for the migration source &apos;{0}&apos;.
        /// </summary>
        internal static string ServerDiffProviderNotLoaded {
            get {
                return ResourceManager.GetString("ServerDiffProviderNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServerDiff: RESULT: {0}.
        /// </summary>
        internal static string ServerDiffResult {
            get {
                return ResourceManager.GetString("ServerDiffResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No session group found with ID: {0}.
        /// </summary>
        internal static string SessionGroupNotFound {
            get {
                return ResourceManager.GetString("SessionGroupNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session specified is not a version control session: {0}.
        /// </summary>
        internal static string SessionIsNotVCSession {
            get {
                return ResourceManager.GetString("SessionIsNotVCSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session specified is not a work item session: {0}.
        /// </summary>
        internal static string SessionIsNotWITSession {
            get {
                return ResourceManager.GetString("SessionIsNotWITSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No session of type {0} with Id {1} was found.
        /// </summary>
        internal static string SessionWithIdAndTypeNotFound {
            get {
                return ResourceManager.GetString("SessionWithIdAndTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No session of type {0} was found.
        /// </summary>
        internal static string SessionWithTypeNotFound {
            get {
                return ResourceManager.GetString("SessionWithTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VCServerDiff.VerifyContentMatch time to perform diff: {0} seconds.
        /// </summary>
        internal static string VCServerDiffTimeToRun {
            get {
                return ResourceManager.GetString("VCServerDiffTimeToRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WITServerDiff.VerifyContentMatch time to perform diff: {0} seconds.
        /// </summary>
        internal static string WITServerDiffTimeToRun {
            get {
                return ResourceManager.GetString("WITServerDiffTimeToRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The contents of work item with Id &apos;{0}&apos; in &apos;{1}&apos; does not match the work item &apos;{2}&apos; in &apos;{3}&apos;.
        /// </summary>
        internal static string WorkItemDataMismatch {
            get {
                return ResourceManager.GetString("WorkItemDataMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The definition of work item with Id &apos;{0}&apos; in &apos;{1}&apos; does not match the work item &apos;{2}&apos; in &apos;{3}&apos;.
        /// </summary>
        internal static string WorkItemDefinitionMismatch {
            get {
                return ResourceManager.GetString("WorkItemDefinitionMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of fields in the work item definitions do not match: {0} for {1}; {2} for {3}.
        /// </summary>
        internal static string WorkItemFieldCountsDoNotMatch {
            get {
                return ResourceManager.GetString("WorkItemFieldCountsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;{0}&apos; was defined for &apos;{1}&apos; but not for &apos;{2}&apos;.
        /// </summary>
        internal static string WorkItemMissingField {
            get {
                return ResourceManager.GetString("WorkItemMissingField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No corresponding work item as found in &apos;{0}&apos; for the work item with Id in &apos;{1}&apos; in &apos;{2}&apos;.
        /// </summary>
        internal static string WorkItemNotMirrored {
            get {
                return ResourceManager.GetString("WorkItemNotMirrored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error comparing work items: {0}.
        /// </summary>
        internal static string WorkItemProcessingError {
            get {
                return ResourceManager.GetString("WorkItemProcessingError", resourceCulture);
            }
        }
    }
}
