//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.21
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.21.
// 
namespace Microsoft.TeamFoundation.Converters.Reporting
{
    using System.Xml.Serialization;
    using System.Collections;

    // 
    // This source code was auto-generated by xsd, Version=2.0.40825.0.
    // 

    // WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING!!!!!!!
    // KPNAGA - Modifications done after generating this file from xsd.exe
    //
    //      1.) Add namespace 
    //      2.) Make the classes Report, ReportSummary, ReportStatistics, ReportSummaryTarget, ReportFile and ReportSummarySource partial.
    //      3.) Make the class ReportSummarySourceAndDestination empty. They are being implemented in other .cs files;
    //      4.) Added using System.Collections; to the beginning
    //      5.) 
    //
    // If this file is regenerated using xsd.exe, please make the above changes on 
    // the auto-generated file.
    // WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING!!!!!!!

    //Changes to be made after generating this file from Xsd.exe
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.21")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Report
    {

        private ReportType typeField;

        private ReportConverter converterField;

        private string runByField;

        private ReportSourceSystem sourceSystemField;

        private ReportTargetSystem targetSystemField;

        private string titleField;

        private ReportUserInput userInputField;

        // private ReportIssue[] issuesField;
        private ArrayList issuesField;

        private ReportSummary summaryField;

        private ReportStatistics statisticsField;

        //private ReportFile[] outputField;
        private ArrayList outputField;

        private ReportDependencies dependenciesField;

        private string versionField;

        /// <remarks/>
        public ReportType Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        public ReportConverter Converter
        {
            get
            {
                return this.converterField;
            }
            set
            {
                this.converterField = value;
            }
        }

        /// <remarks/>
        public string RunBy
        {
            get
            {
                return this.runByField;
            }
            set
            {
                this.runByField = value;
            }
        }

        /// <remarks/>
        public ReportSourceSystem SourceSystem
        {
            get
            {
                return this.sourceSystemField;
            }
            set
            {
                this.sourceSystemField = value;
            }
        }

        /// <remarks/>
        public ReportTargetSystem TargetSystem
        {
            get
            {
                return this.targetSystemField;
            }
            set
            {
                this.targetSystemField = value;
            }
        }

        /// <remarks/>
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        public ReportUserInput UserInput
        {
            get
            {
                return this.userInputField;
            }
            set
            {
                this.userInputField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Issue", Type = typeof(ReportIssue), IsNullable = false)]
        // public ReportIssue[] Issues
        public ArrayList Issues
        {
            get
            {
                return this.issuesField;
            }
        }


        /// <remarks/>
        public ReportSummary Summary
        {
            get
            {
                return this.summaryField;
            }
            set
            {
                this.summaryField = value;
            }
        }

        /// <remarks/>
        public ReportStatistics Statistics
        {
            get
            {
                return this.statisticsField;
            }
            set
            {
                this.statisticsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("File", Type = typeof(ReportFile), IsNullable = false)]
        //public ReportFile[] Output
        public ArrayList Output
        {
            get
            {
                return this.outputField;
            }
        }

        /// <remarks/>
        public ReportDependencies Dependencies
        {
            get
            {
                return this.dependenciesField;
            }
            set
            {
                this.dependenciesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.21")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum ReportType
    {

        /// <remarks/>
        PreMigration,

        /// <remarks/>
        PostMigration,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.21")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum ReportConverter
    {

        /// <remarks/>
        VSSConverter,

        /// <remarks/>
        SDConverter,

        /// <remarks/>
        PSConverter,

        /// <remarks/>
        CQConverter,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.21")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum ReportSourceSystem
    {

        /// <remarks/>
        ClearCase,

        /// <remarks/>
        ClearQuest,

        /// <remarks/>
        CSV,

        /// <remarks/>
        PS,

        /// <remarks/>
        PVCS,

        /// <remarks/>
        SD,

        /// <remarks/>
        VSS,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.21")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum ReportTargetSystem
    {

        /// <remarks/>
        WorkItemTracking,

        /// <remarks/>
        VersionControl,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.21")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ReportUserInput
    {

        private string commandLineField;

        private string[] optionsField;

        private bool usingUIField;

        /// <remarks/>
        public string CommandLine
        {
            get
            {
                return this.commandLineField;
            }
            set
            {
                this.commandLineField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Option", IsNullable = false)]
        public string[] Options
        {
            get
            {
                return this.optionsField;
            }
            set
            {
                this.optionsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool UsingUI
        {
            get
            {
                return this.usingUIField;
            }
            set
            {
                this.usingUIField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.21")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ReportIssue
    {

        private string itemField;

        private string locationField;

        private string messageField;

        private string[] additionalInfosField;

        private string issueIDField;

        private ReportIssueType typeField;

        private string groupField;

        /// <remarks/>
        public string Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        public string Location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }

        /// <remarks/>
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("AdditionalInfo", IsNullable = false)]
        public string[] AdditionalInfos
        {
            get
            {
                return this.additionalInfosField;
            }
            set
            {
                this.additionalInfosField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IssueID
        {
            get
            {
                return this.issueIDField;
            }
            set
            {
                this.issueIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ReportIssueType Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Group
        {
            get
            {
                return this.groupField;
            }
            set
            {
                this.groupField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.21")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum ReportIssueType
    {

        /// <remarks/>
        Critical,

        /// <remarks/>
        Error,

        /// <remarks/>
        Warning,

        /// <remarks/>
        Info,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.21")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ReportSummary
    {

        private ReportSummaryTypeOfMigration typeOfMigrationField;

        private string sourceActionStartTimeField;

        private string sourceActionEndTimeField;

        private string startTimeField;

        private string endTimeField;

        private string totalTimeField;

        private string statusField;

        private ReportSummarySourceAndDestination sourceAndDestinationField;

        /// <remarks/>
        public ReportSummaryTypeOfMigration TypeOfMigration
        {
            get
            {
                return this.typeOfMigrationField;
            }
            set
            {
                this.typeOfMigrationField = value;
            }
        }

        /// <remarks/>
        public string SourceActionStartTime
        {
            get
            {
                return this.sourceActionStartTimeField;
            }
            set
            {
                this.sourceActionStartTimeField = value;
            }
        }

        /// <remarks/>
        public string SourceActionEndTime
        {
            get
            {
                return this.sourceActionEndTimeField;
            }
            set
            {
                this.sourceActionEndTimeField = value;
            }
        }

        /// <remarks/>
        public string StartTime
        {
            get
            {
                return this.startTimeField;
            }
            set
            {
                this.startTimeField = value;
            }
        }

        /// <remarks/>
        public string EndTime
        {
            get
            {
                return this.endTimeField;
            }
            set
            {
                this.endTimeField = value;
            }
        }

        /// <remarks/>
        public string TotalTime
        {
            get
            {
                return this.totalTimeField;
            }
            set
            {
                this.totalTimeField = value;
            }
        }

        /// <remarks/>
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        public ReportSummarySourceAndDestination SourceAndDestination
        {
            get
            {
                return this.sourceAndDestinationField;
            }
            set
            {
                this.sourceAndDestinationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.21")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum ReportSummaryTypeOfMigration
    {

        /// <remarks/>
        Full,

        /// <remarks/>
        Incremental,
    }



    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.21")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ReportStatistics
    {

        private bool hasCriticalErrorField;

        private long numberOfErrorsField;

        private long numberOfWarningsField;

        private long numberOfItemsField;

        //private ReportStatisticsStatisicsDetails statisicsDetailsField;
        private ReportStatisticsStatisicsDetails statisicsDetailsField = new ReportStatisticsStatisicsDetails();

        /// <remarks/>
        public bool HasCriticalError
        {
            get
            {
                return this.hasCriticalErrorField;
            }
            set
            {
                this.hasCriticalErrorField = value;
            }
        }

        /// <remarks/>
        public long NumberOfErrors
        {
            get
            {
                return this.numberOfErrorsField;
            }
            set
            {
                this.numberOfErrorsField = value;
            }
        }

        /// <remarks/>
        public long NumberOfWarnings
        {
            get
            {
                return this.numberOfWarningsField;
            }
            set
            {
                this.numberOfWarningsField = value;
            }
        }

        /// <remarks/>
        public long NumberOfItems
        {
            get
            {
                return this.numberOfItemsField;
            }
            set
            {
                this.numberOfItemsField = value;
            }
        }

        /// <remarks/>
        public ReportStatisticsStatisicsDetails StatisicsDetails
        {
            get
            {
                return this.statisicsDetailsField;
            }
            set
            {
                this.statisicsDetailsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.21")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ReportSummarySourceAndDestination
    {


    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.21")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ReportStatisticsStatisicsDetails
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.21")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ReportFile
    {

        private string nameField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.21")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ReportDependencies
    {

        private System.Xml.XmlElement[] anyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.21")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class ReportSchema
    {

        private Report itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Report")]
        public Report Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }
}
