//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.TeamFoundation.Migration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.TeamFoundation.Migration.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Attempting to attach a business model manager to multiple models..
        /// </summary>
        internal static string ErrorAttachManagerToMultipleModel {
            get {
                return ResourceManager.GetString("ErrorAttachManagerToMultipleModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Attempting to attach multiple business model manager to a model..
        /// </summary>
        internal static string ErrorAttachMultipleManagerToBusinessModel {
            get {
                return ResourceManager.GetString("ErrorAttachMultipleManagerToBusinessModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Setting of default command timeout value does not contain valid value..
        /// </summary>
        internal static string ErrorDefaultTimeoutSettingInvalid {
            get {
                return ResourceManager.GetString("ErrorDefaultTimeoutSettingInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: There are inconsistent data stored for {0}..
        /// </summary>
        internal static string ErrorGenericDBInconsistency {
            get {
                return ResourceManager.GetString("ErrorGenericDBInconsistency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Cannot find a session group config with the provided Id..
        /// </summary>
        internal static string ErrorInternalIdOfSessionGroupConfigNotExist {
            get {
                return ResourceManager.GetString("ErrorInternalIdOfSessionGroupConfigNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Cannot change the Provider, Server and Source of a migration source. Please consider to create a new one..
        /// </summary>
        internal static string ErrorInvalidMigrationSourceChange {
            get {
                return ResourceManager.GetString("ErrorInvalidMigrationSourceChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Cannot find the migration data folder at {0}..
        /// </summary>
        internal static string ErrorMigrationDataFolderNotFound {
            get {
                return ResourceManager.GetString("ErrorMigrationDataFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Configuration file &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string ErrorMissingConfigurationFile {
            get {
                return ResourceManager.GetString("ErrorMissingConfigurationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Failed to find required event sink..
        /// </summary>
        internal static string ErrorMissingEventSink {
            get {
                return ResourceManager.GetString("ErrorMissingEventSink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Cannot find the provider for the event sink..
        /// </summary>
        internal static string ErrorMissingEventSinkProvider {
            get {
                return ResourceManager.GetString("ErrorMissingEventSinkProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Global configuration file {0} does not exist in current working directory {1}..
        /// </summary>
        internal static string ErrorMissingGlobalConfigFile {
            get {
                return ResourceManager.GetString("ErrorMissingGlobalConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Cannot find the provider for the linking engine..
        /// </summary>
        internal static string ErrorMissingLinkingEngineProvider {
            get {
                return ResourceManager.GetString("ErrorMissingLinkingEngineProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Missing migration source configuration..
        /// </summary>
        internal static string ErrorMissingMigrSourceConfig {
            get {
                return ResourceManager.GetString("ErrorMissingMigrSourceConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Cannot find the provider of a migration source..
        /// </summary>
        internal static string ErrorMissingProviderForMigrationSource {
            get {
                return ResourceManager.GetString("ErrorMissingProviderForMigrationSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Cannot find the session configuration in a session group..
        /// </summary>
        internal static string ErrorMissingSessionConfig {
            get {
                return ResourceManager.GetString("ErrorMissingSessionConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: More than one active configuration for a session group were found..
        /// </summary>
        internal static string ErrorMultiActiveConfigExist {
            get {
                return ResourceManager.GetString("ErrorMultiActiveConfigExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: More than one configuration have the same internal Id..
        /// </summary>
        internal static string ErrorMultiConfigWithSameId {
            get {
                return ResourceManager.GetString("ErrorMultiConfigWithSameId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: More than one migration source have the same unique Id..
        /// </summary>
        internal static string ErrorMultiMigrationSourceWithSameUniqueId {
            get {
                return ResourceManager.GetString("ErrorMultiMigrationSourceWithSameUniqueId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: More than one provider have the same reference name..
        /// </summary>
        internal static string ErrorMultiProviderWithReferenceName {
            get {
                return ResourceManager.GetString("ErrorMultiProviderWithReferenceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: More than one session configuration have the same unique Id..
        /// </summary>
        internal static string ErrorMultiSessionConfigWithSameId {
            get {
                return ResourceManager.GetString("ErrorMultiSessionConfigWithSameId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: More than one session group configuration have the same unique Id..
        /// </summary>
        internal static string ErrorMultiSessionGroupConfigWithSameId {
            get {
                return ResourceManager.GetString("ErrorMultiSessionGroupConfigWithSameId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: More than one session group have the same unique Id..
        /// </summary>
        internal static string ErrorMultiSessionGroupWithSameId {
            get {
                return ResourceManager.GetString("ErrorMultiSessionGroupWithSameId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: The &apos;UseWindowsService&apos; configuration setting contains invalid value..
        /// </summary>
        internal static string ErrorUseWindowsServiceSettingInvalid {
            get {
                return ResourceManager.GetString("ErrorUseWindowsServiceSettingInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Attempting to use the same ConfigurationValidator for more than once..
        /// </summary>
        internal static string ErrorUsingConfigValidatorMultiTimes {
            get {
                return ResourceManager.GetString("ErrorUsingConfigValidatorMultiTimes", resourceCulture);
            }
        }
    }
}
