//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.TeamFoundation.Converters.WorkItemTracking.CQ {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CQResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CQResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CQConverter.CQResource", typeof(CQResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is a core field in Team Foundation Work Item Tracking and it is recommended that you use this field because it best suits the purpose.
        /// </summary>
        internal static string CoreFieldComment {
            get {
                return ResourceManager.GetString("CoreFieldComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF61100: Unable to start {0}. Base Entity &apos;{1}&apos; has to be converted. Include the base entity in migration by adding the name in SourceEntity element in &apos;{2}&apos;..
        /// </summary>
        internal static string CQ_BASE_ENTITY_REQ {
            get {
                return ResourceManager.GetString("CQ_BASE_ENTITY_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF61118: ClearQuest API call failed with the following error:
        ///{0}
        ///Refer ClearQuest documentation for more help..
        /// </summary>
        internal static string CQ_COM_ERROR {
            get {
                return ResourceManager.GetString("CQ_COM_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF61119: Connection to ClearQuest failed with the following error:
        ///{0}
        ///- Check the ClearQuest information in the configuration file {1}. 
        ///- Check to see if you can access ClearQuest from the ClearQuest client..
        /// </summary>
        internal static string CQ_CONNECTION_ERROR {
            get {
                return ResourceManager.GetString("CQ_CONNECTION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping import for Entity &apos;{0}&apos; as it does not exist in &apos;{1}&apos;..
        /// </summary>
        internal static string CQ_DROP_ENTITY {
            get {
                return ResourceManager.GetString("CQ_DROP_ENTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF61121: The converter could not migrate parent record &apos;{0}&apos; of &apos;{1}&apos; because of the following error: {2}.  Please fix the source of the error and run the converter again to migrate the work item..
        /// </summary>
        internal static string CQ_DUP_REC_FAILED {
            get {
                return ResourceManager.GetString("CQ_DUP_REC_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Item &apos;{0}&apos; duplicate of &apos;{1}&apos;.
        /// </summary>
        internal static string CQ_DUPLICATE_LINK_COMMENT {
            get {
                return ResourceManager.GetString("CQ_DUPLICATE_LINK_COMMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping link creation for work item &apos;{0}&apos; as duplicate of work item type &apos;{1}&apos;, which is not in the migration list..
        /// </summary>
        internal static string CQ_DUPLICATE_LINK_SKIP {
            get {
                return ResourceManager.GetString("CQ_DUPLICATE_LINK_SKIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the password for ClearQuest user &apos;{0}&apos;: .
        /// </summary>
        internal static string CQ_ENTER_PWD {
            get {
                return ResourceManager.GetString("CQ_ENTER_PWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entities selected for conversion - .
        /// </summary>
        internal static string CQ_ENTITY_MIGRATED {
            get {
                return ResourceManager.GetString("CQ_ENTITY_MIGRATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF61101: Unable to start {0}. Entity Type &apos;{1}&apos; does not exist in ClearQuest database. Please fix SourceEntity element in &apos;{2}&apos; so that it points to a valid ClearQuest entity..
        /// </summary>
        internal static string CQ_ENTITY_NOT_EXIST {
            get {
                return ResourceManager.GetString("CQ_ENTITY_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity &apos;{0}&apos; will not be converted as it is not connected with the base entity &apos;{1}&apos;..
        /// </summary>
        internal static string CQ_ENTITY_NOT_MIG {
            get {
                return ResourceManager.GetString("CQ_ENTITY_NOT_MIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work item type &apos;{0}&apos; cannot be created because it already exists on your Team Foundation Server..
        /// </summary>
        internal static string CQ_ENTITY_NOT_MIG_EXIST {
            get {
                return ResourceManager.GetString("CQ_ENTITY_NOT_MIG_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF61102: Migration stopped. Field Map validation failed for file &apos;{0}&apos;. Field(s) &apos;{1}&apos; does not exist in ClearQuest Entity &apos;{2}&apos;. Delete the fields that do not exist in the entity from the field mapping file..
        /// </summary>
        internal static string CQ_FLD_NOT_EXIST {
            get {
                return ResourceManager.GetString("CQ_FLD_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing field &apos;{0}&apos; attribute from Read-only to Editable.
        /// </summary>
        internal static string CQ_FLD_READONLY_CHANGED {
            get {
                return ResourceManager.GetString("CQ_FLD_READONLY_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not migrating the Hooks behavior for Field &apos;{0}&apos;.
        /// </summary>
        internal static string CQ_FLD_SKIP_HOOK {
            get {
                return ResourceManager.GetString("CQ_FLD_SKIP_HOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed on:{0}, Changed By:{1}, Action:{2}, from state:&apos;{3}&apos; to &apos;{4}&apos;.
        /// </summary>
        internal static string CQ_HISTORY_STRING {
            get {
                return ResourceManager.GetString("CQ_HISTORY_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF61115: Unable to start {0}. Unable to find details for Connection &apos;{1}&apos;, User Database &apos;{2}&apos;. Check these values in configuration file &apos;{3}&apos;.
        /// </summary>
        internal static string CQ_INVALID_CONN {
            get {
                return ResourceManager.GetString("CQ_INVALID_CONN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF61106: Unable to start {0}. The query name &apos;{1}&apos; was not recognized. Correct the query name in the configuration file &apos;{2}&apos; and try again..
        /// </summary>
        internal static string CQ_INVALID_QUERY {
            get {
                return ResourceManager.GetString("CQ_INVALID_QUERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link from &apos;{0}&apos; to &apos;{1}&apos;.
        /// </summary>
        internal static string CQ_LINK_COMMENT {
            get {
                return ResourceManager.GetString("CQ_LINK_COMMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF61105: Unable to start {0}. The ClearQuest credentials you provided do not have admin rights on the ClearQuest database. Verify that the user specified in &lt;UserID&gt; element in the configuration file &apos;{1}&apos; has admin rights..
        /// </summary>
        internal static string CQ_NO_ADMIN_RIGHT {
            get {
                return ResourceManager.GetString("CQ_NO_ADMIN_RIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF61117: Query &apos;{0}&apos; specified in configuration file &apos;{1}&apos; does not contain &apos;dbid&apos; field. Please edit the query to include &apos;dbid&apos; field..
        /// </summary>
        internal static string CQ_NO_DBID_IN_QUERY {
            get {
                return ResourceManager.GetString("CQ_NO_DBID_IN_QUERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF61114: Unable to start {0}. The converter could not find a work item type definition (WITD) file in the Schema Map file &apos;{1}&apos;. The WITD file is needed to create the work item type &apos;{2}&apos;..
        /// </summary>
        internal static string CQ_NO_WITD_FILE {
            get {
                return ResourceManager.GetString("CQ_NO_WITD_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF61112: Unable to start {0}. The query is not based on the Submit type entity. CQConverter supports only submit type entities for conversion. Correct the query in the configuration file &apos;{1}&apos; and try again..
        /// </summary>
        internal static string CQ_NOT_SUBMIT_ENTITY {
            get {
                return ResourceManager.GetString("CQ_NOT_SUBMIT_ENTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF61116: The converter could not create the output directory &apos;{0}&apos; specified in &apos;{1}&apos; because of the following error: {2}. Correct the directory name in the configuration file &apos;{1}&apos; and try again..
        /// </summary>
        internal static string CQ_OUTDIR_CREATION_FAILED {
            get {
                return ResourceManager.GetString("CQ_OUTDIR_CREATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing record for &apos;{0}&apos;..
        /// </summary>
        internal static string CQ_PROCESSING_REC {
            get {
                return ResourceManager.GetString("CQ_PROCESSING_REC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrated {0} of {1} records.
        /// </summary>
        internal static string CQ_PROGRESS {
            get {
                return ResourceManager.GetString("CQ_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work item &apos;{0}&apos; is already migrated..
        /// </summary>
        internal static string CQ_REC_MIGRATED {
            get {
                return ResourceManager.GetString("CQ_REC_MIGRATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF611202: The converter could not migrate the referenced record with value &apos;{0}&apos; associated with record &apos;{1}&apos; because of the following error: {2}.  Please fix the source of the error and run the converter again to migrate the work item..
        /// </summary>
        internal static string CQ_REF_REC_FAILED {
            get {
                return ResourceManager.GetString("CQ_REF_REC_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The work item &apos;{0}&apos; of type &apos;{1}&apos; contains a reference to itself in field &apos;{2}&apos;. Team Foundation does not support relating a work item to itself. .
        /// </summary>
        internal static string CQ_SELF_REFERENCE {
            get {
                return ResourceManager.GetString("CQ_SELF_REFERENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; field is of the type &apos;User List&apos;. The converter is converting it to a &apos;Simple String&apos; field because Team Foundation does not support multi-value fields..
        /// </summary>
        internal static string CQ_USER_LIST_CHANGED {
            get {
                return ResourceManager.GetString("CQ_USER_LIST_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating field map file &apos;{0}&apos; .
        /// </summary>
        internal static string CQ_VALIDATE_FLD_MAP {
            get {
                return ResourceManager.GetString("CQ_VALIDATE_FLD_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF61103: Unable to start {0}. Unable to find details about ClearQuest connection. Please make sure that ClearQuest is installed on your system and you have connected at least once from the ClearQuest client running under the user credentials you are using to run the converter..
        /// </summary>
        internal static string CQ_VER_NOT_SUPPORT {
            get {
                return ResourceManager.GetString("CQ_VER_NOT_SUPPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF61110: Migration halted. The converter could not create work item &apos;{0}&apos; because of the following error: {1}..
        /// </summary>
        internal static string CQ_WI_CREATION_FAILED {
            get {
                return ResourceManager.GetString("CQ_WI_CREATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF61111: The converter could not convert work item &apos;{0}&apos; because of the following error: {1}. Please fix the source of the error and run the converter again to migrate the work item..
        /// </summary>
        internal static string CQ_WI_MIG_FAILED {
            get {
                return ResourceManager.GetString("CQ_WI_MIG_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF61120: The converter could not migrate Clear Quest item with dbid=&apos;{0}&apos; because of the following error: {1}.  Please fix the source of the error and run the converter again to migrate the work item..
        /// </summary>
        internal static string CQ_WI_READ_FAILED {
            get {
                return ResourceManager.GetString("CQ_WI_READ_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating Schema for Work Item Type &apos;{0}&apos;.
        /// </summary>
        internal static string SchemaCreation {
            get {
                return ResourceManager.GetString("SchemaCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema Map.
        /// </summary>
        internal static string SchemaMap {
            get {
                return ResourceManager.GetString("SchemaMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating work item file &apos;{0}&apos;.
        /// </summary>
        internal static string SchemaValidation {
            get {
                return ResourceManager.GetString("SchemaValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Map.
        /// </summary>
        internal static string UserMap {
            get {
                return ResourceManager.GetString("UserMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Item Type Definition.
        /// </summary>
        internal static string Witd {
            get {
                return ResourceManager.GetString("Witd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Item Field Map.
        /// </summary>
        internal static string WitFieldMap {
            get {
                return ResourceManager.GetString("WitFieldMap", resourceCulture);
            }
        }
    }
}
