//<autogenerated/>
using System.Reflection;
using System.Runtime.InteropServices;
[assembly: AssemblyTitle("SharePoint TIP Adapter - Work Items")]
[assembly: AssemblyDescription("SharePoint TIP Adapter - Work Items")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyTrademark("Microsoft")]
[assembly: AssemblyCulture("en")]
[assembly: ComVisible(false)]
[assembly: Guid("a41d7331-11ec-46c1-ab66-7bfc8ce36e9b")]
[assembly: System.CLSCompliant(false)]