//<autogenerated/>
using System.Reflection;
using System.Runtime.InteropServices;
[assembly: AssemblyTitle("SharePoint TIP Adapter - Version Control")]
[assembly: AssemblyDescription("SharePoint TIP Adapter - Version Control")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyTrademark("Microsoft")]
[assembly: AssemblyCulture("en")]
[assembly: ComVisible(false)]
[assembly: Guid("66587ed1-d015-4ded-aab1-aefbfccfd751")]
[assembly: System.CLSCompliant(false)]
