//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFSIntegrationAdmin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TFSIntegrationAdmin.ResourceStrings", typeof(ResourceStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Ctrl-C to cancel the command execution..
        /// </summary>
        internal static string CancelKeyInfo {
            get {
                return ResourceManager.GetString("CancelKeyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &apos;{0}&apos; failed..
        /// </summary>
        internal static string CommandExecutionFailFormat {
            get {
                return ResourceManager.GetString("CommandExecutionFailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &apos;{0}&apos; executed successfully..
        /// </summary>
        internal static string CommandExecutionSucceedFormat {
            get {
                return ResourceManager.GetString("CommandExecutionSucceedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Group &apos;{0}&apos; has been successfully deleted..
        /// </summary>
        internal static string DeleteSessionGroupSucceedInfoFormat {
            get {
                return ResourceManager.GetString("DeleteSessionGroupSucceedInfoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TFS Integration data folder specified in the configuration file &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string ErrorDataFolderInvalidPathInfoFormat {
            get {
                return ResourceManager.GetString("ErrorDataFolderInvalidPathInfoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find or modify the  TFS Integration data folder &apos;{0}&apos;..
        /// </summary>
        internal static string ErrorDataFolderNotFoundOrUnmodifiableInfoFormat {
            get {
                return ResourceManager.GetString("ErrorDataFolderNotFoundOrUnmodifiableInfoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error - adding user account to TFSIPEXEC role in the TFS_IntegrationPlatform DB failed..
        /// </summary>
        internal static string ErrorFailToAddAccountToTFSIPEXECRole {
            get {
                return ResourceManager.GetString("ErrorFailToAddAccountToTFSIPEXECRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error - execution of command &apos;{0}&apos; requires Administrator&apos;s privilege..
        /// </summary>
        internal static string ErrorNeedAdminPrivilegeToRunCommandFormat {
            get {
                return ResourceManager.GetString("ErrorNeedAdminPrivilegeToRunCommandFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot perform compression - a session group is running..
        /// </summary>
        internal static string ErrorSessionGroupIsRunning {
            get {
                return ResourceManager.GetString("ErrorSessionGroupIsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TFS Integration data folder specified in the configuration file &apos;{0}&apos; does not exist. You do not have permission to create the folder..
        /// </summary>
        internal static string ErrorUnauthorizedAccessCreatingDataFolderInfoFormat {
            get {
                return ResourceManager.GetString("ErrorUnauthorizedAccessCreatingDataFolderInfoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to change the Access Control settings of the  TFS Integration data folder &apos;{0}&apos;..
        /// </summary>
        internal static string ErrorUnauthorizedAccessUpdatingDataFolderInfoFormat {
            get {
                return ResourceManager.GetString("ErrorUnauthorizedAccessUpdatingDataFolderInfoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation is not supported, because the current operating system is not Microsoft Windows 2000 or later..
        /// </summary>
        internal static string ErrorUnsupportedPlatformUpdatingDataFolderInfo {
            get {
                return ResourceManager.GetString("ErrorUnsupportedPlatformUpdatingDataFolderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided Session Group Unique Id &apos;{0}&apos; does not correspond to any existing session group..
        /// </summary>
        internal static string ExportConfigNonExistSessionGroupIdFormat {
            get {
                return ResourceManager.GetString("ExportConfigNonExistSessionGroupIdFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration has been exported to file &apos;{0}&apos;..
        /// </summary>
        internal static string ExportConfigSuccessInfoFormat {
            get {
                return ResourceManager.GetString("ExportConfigSuccessInfoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no configuration file in the configuration package to import from..
        /// </summary>
        internal static string ImportConfigConfigNotExist {
            get {
                return ResourceManager.GetString("ImportConfigConfigNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration has been successfully imported. The imported configuration name is &apos;{0}&apos; (session group unique id: {1})..
        /// </summary>
        internal static string ImportConfigSuccessInfoFormat {
            get {
                return ResourceManager.GetString("ImportConfigSuccessInfoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service is running: False..
        /// </summary>
        internal static string IntegrationServiceNotRunningInfo {
            get {
                return ResourceManager.GetString("IntegrationServiceNotRunningInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid command line arguments..
        /// </summary>
        internal static string InvalidCommandLineArgInfo {
            get {
                return ResourceManager.GetString("InvalidCommandLineArgInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid command line arguments -.
        /// </summary>
        internal static string InvalidCommandSpecificArgInfo {
            get {
                return ResourceManager.GetString("InvalidCommandSpecificArgInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid Session Group Unique Id..
        /// </summary>
        internal static string InvalidSessionGroupUnqueIdInfoFormat {
            get {
                return ResourceManager.GetString("InvalidSessionGroupUnqueIdInfoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to argument &apos;{0}&apos; is invalid for Command &apos;{1}&apos;. .
        /// </summary>
        internal static string KnownInvalidCommandSpecificArgFormat {
            get {
                return ResourceManager.GetString("KnownInvalidCommandSpecificArgFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session groups that can be deleted: .
        /// </summary>
        internal static string ListSessionGroupSuccessInfoHeader {
            get {
                return ResourceManager.GetString("ListSessionGroupSuccessInfoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid command line arguments - please specify a command to execute..
        /// </summary>
        internal static string MissingCommandInArgInfo {
            get {
                return ResourceManager.GetString("MissingCommandInArgInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running session groups.
        /// </summary>
        internal static string RunningSessionGroupsHeader {
            get {
                return ResourceManager.GetString("RunningSessionGroupsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service hosted in Windows Service.
        /// </summary>
        internal static string StatusServiceHostInfo {
            get {
                return ResourceManager.GetString("StatusServiceHostInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred during the command execution....
        /// </summary>
        internal static string UnhandledExceptionInfo {
            get {
                return ResourceManager.GetString("UnhandledExceptionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string UnknownCommandName {
            get {
                return ResourceManager.GetString("UnknownCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is invalid argument(s) for Command &apos;{0}&apos;. .
        /// </summary>
        internal static string UnknownInvalidCommandSpecificArgFormat {
            get {
                return ResourceManager.GetString("UnknownInvalidCommandSpecificArgFormat", resourceCulture);
            }
        }
    }
}
