//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.TeamFoundation.Converters.WorkItemTracking.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CurConResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CurConResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CQConverter.common.CurConResource", typeof(CurConResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to analysis.
        /// </summary>
        internal static string Analysis {
            get {
                return ResourceManager.GetString("Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis report file: {0}.
        /// </summary>
        internal static string AnalysisReportFile {
            get {
                return ResourceManager.GetString("AnalysisReportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis completed successfully.
        /// </summary>
        internal static string AnalysisSuccessful {
            get {
                return ResourceManager.GetString("AnalysisSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis completed with {0} warning(s), {1} error(s).
        /// </summary>
        internal static string AnalysisWithErrors {
            get {
                return ResourceManager.GetString("AnalysisWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis completed with {0} warning(s).
        /// </summary>
        internal static string AnalysisWithWarnings {
            get {
                return ResourceManager.GetString("AnalysisWithWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command - Analyze.
        /// </summary>
        internal static string AnalyzeCommand {
            get {
                return ResourceManager.GetString("AnalyzeCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIG.
        /// </summary>
        internal static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration Settings file - {0}.
        /// </summary>
        internal static string ConfigFile {
            get {
                return ResourceManager.GetString("ConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing canceled by the user..
        /// </summary>
        internal static string ControlKeyPressed {
            get {
                return ResourceManager.GetString("ControlKeyPressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} [/?|h|help | /m[igrationsettings:&lt;configuration file&gt;] 
        ///
        /// configration file  The generator configuration file. 
        /// /?|h|help          Display help
        ///
        ///Example:
        /// &gt; {0}.exe /m:MyConfiguration.xml.
        /// </summary>
        internal static string CurConHelpMessage {
            get {
                return ResourceManager.GetString("CurConHelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid assembly name: {0}.
        /// </summary>
        internal static string InvalidAssemblyName {
            get {
                return ResourceManager.GetString("InvalidAssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF61036: Unrecognized or incomplete command {0}.
        /// </summary>
        internal static string InvalidCommand {
            get {
                return ResourceManager.GetString("InvalidCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF61120: The file &apos;{0}&apos; is not a valid schema map file. Please check the format of the file in the help documentation..
        /// </summary>
        internal static string InvalidSchemaMap {
            get {
                return ResourceManager.GetString("InvalidSchemaMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source field &apos;{0}&apos; is mapped more than once in &apos;{1}&apos;.
        /// </summary>
        internal static string InvalidSourceFieldMap {
            get {
                return ResourceManager.GetString("InvalidSourceFieldMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source id {0} in configuration file {1} is invalid..
        /// </summary>
        internal static string InvalidSourceId {
            get {
                return ResourceManager.GetString("InvalidSourceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target field &apos;{0}&apos; is mapped more than once in &apos;{1}&apos;.
        /// </summary>
        internal static string InvalidTargetFieldMap {
            get {
                return ResourceManager.GetString("InvalidTargetFieldMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command - Migrate.
        /// </summary>
        internal static string MigrateCommand {
            get {
                return ResourceManager.GetString("MigrateCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to migration.
        /// </summary>
        internal static string Migration {
            get {
                return ResourceManager.GetString("Migration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration report file: {0}.
        /// </summary>
        internal static string MigrationReportFile {
            get {
                return ResourceManager.GetString("MigrationReportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration completed successfully.
        /// </summary>
        internal static string MigrationSuccessful {
            get {
                return ResourceManager.GetString("MigrationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration completed with {0} warning(s), {1} error(s).
        /// </summary>
        internal static string MigrationWithErrors {
            get {
                return ResourceManager.GetString("MigrationWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration completed with {0} warning(s).
        /// </summary>
        internal static string MigrationWithWarnings {
            get {
                return ResourceManager.GetString("MigrationWithWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Entity &apos;{0}&apos; exists more than once in &apos;{1}&apos;.
        /// </summary>
        internal static string MultipleSourceEntity {
            get {
                return ResourceManager.GetString("MultipleSourceEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Work Item Type &apos;{0}&apos; exists more than once in &apos;{1}&apos;.
        /// </summary>
        internal static string MultipleTargetEntity {
            get {
                return ResourceManager.GetString("MultipleTargetEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Schema Map defined in &apos;{0}&apos;.
        /// </summary>
        internal static string NoSchemaMap {
            get {
                return ResourceManager.GetString("NoSchemaMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No User Map defined in &apos;{0}&apos;.
        /// </summary>
        internal static string NoUserMap {
            get {
                return ResourceManager.GetString("NoUserMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null &apos;from&apos; field specified in the map file &apos;{0}&apos;.
        /// </summary>
        internal static string NullFromField {
            get {
                return ResourceManager.GetString("NullFromField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF61116: The converter could not create the output directory because of the following error: {0}. Correct the directory name in the configuration file &apos;{1}&apos; or check the file permissions and try again..
        /// </summary>
        internal static string OutputDirCreationFailed {
            get {
                return ResourceManager.GetString("OutputDirCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema Map file - {0}.
        /// </summary>
        internal static string SchemaMapFile {
            get {
                return ResourceManager.GetString("SchemaMapFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF61037: Missing Argument /s:&lt;schema map file&gt;. The Schema Map xml file parameter is required with the Migrate command..
        /// </summary>
        internal static string SchemaMapMandatory {
            get {
                return ResourceManager.GetString("SchemaMapMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF61038: Unsupported Argument /s:{0}. The Schema Map xml file parameter is not used with the Analyze command..
        /// </summary>
        internal static string SchemaMapNotRequired {
            get {
                return ResourceManager.GetString("SchemaMapNotRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resolve following user names: {0}.
        /// </summary>
        internal static string UnresolvedUsers {
            get {
                return ResourceManager.GetString("UnresolvedUsers", resourceCulture);
            }
        }
    }
}
