//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version:2.0.41129.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.41129.0.
// 
namespace Microsoft.TeamFoundation.Converters.WorkItemTracking.Common
{
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class ValueMap
    {

        private string fromField;

        private string toField;

        public ValueMap()
        {
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string from
        {
            get
            {
                return this.fromField;
            }
            set
            {
                this.fromField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string to
        {
            get
            {
                return this.toField;
            }
            set
            {
                this.toField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    public partial class FieldMapsFieldMapValueMaps
    {

        private ValueMap[] valueMapField;

        private string referField;

        private string defaultValueField;

        private string idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ValueMap")]
        public ValueMap[] ValueMap
        {
            get
            {
                return this.valueMapField;
            }
            set
            {
                this.valueMapField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string refer
        {
            get
            {
                return this.referField;
            }
            set
            {
                this.referField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string defaultValue
        {
            get
            {
                return this.defaultValueField;
            }
            set
            {
                this.defaultValueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    public partial class FieldMapsFieldMapAction
    {

        private string itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    public partial class FieldMapsFieldMap
    {

        private FieldMapsFieldMapAction[] actionsField;

        private FieldMapsFieldMapValueMaps valueMapsField;

        private string fromField;

        private string toField;

        private string excludeField;

        public FieldMapsFieldMap()
        {
            this.excludeField = "false";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Action", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public FieldMapsFieldMapAction[] Actions
        {
            get
            {
                return this.actionsField;
            }
            set
            {
                this.actionsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FieldMapsFieldMapValueMaps ValueMaps
        {
            get
            {
                return this.valueMapsField;
            }
            set
            {
                this.valueMapsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string from
        {
            get
            {
                return this.fromField;
            }
            set
            {
                this.fromField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string to
        {
            get
            {
                return this.toField;
            }
            set
            {
                this.toField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("false")]
        public string exclude
        {
            get
            {
                return this.excludeField;
            }
            set
            {
                this.excludeField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class FieldMaps
    {

        private FieldMapsFieldMap[] fieldMapField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FieldMap", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FieldMapsFieldMap[] FieldMap
        {
            get
            {
                return this.fieldMapField;
            }
            set
            {
                this.fieldMapField = value;
            }
        }
    }
}