//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.TeamFoundation.Migration.Toolkit {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MigrationToolkitResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MigrationToolkitResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.TeamFoundation.Migration.Toolkit.MigrationToolkitResources", typeof(MigrationToolkitResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnalysisAddin.
        /// </summary>
        public static string AnalysisAddinKeyName {
            get {
                return ResourceManager.GetString("AnalysisAddinKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did not find AnalysisAddin with ID &apos;{0}&apos;.
        /// </summary>
        public static string AnalysisAddinNotFound {
            get {
                return ResourceManager.GetString("AnalysisAddinNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping this synchronization pass because AnalysisAddin of type &apos;{0}&apos; returned false for ProceedToAnalysis().
        /// </summary>
        public static string AnalysisAddinSkippingPass {
            get {
                return ResourceManager.GetString("AnalysisAddinSkippingPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly name must contain a valid assembly qualified type name..
        /// </summary>
        public static string AssemblyQualNameInvalid {
            get {
                return ResourceManager.GetString("AssemblyQualNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChangeGroupManager of source {0} has already been registered in session {1}..
        /// </summary>
        public static string ChangeGroupManagerExists {
            get {
                return ResourceManager.GetString("ChangeGroupManagerExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChangeGroupManager of source {0} is not registered..
        /// </summary>
        public static string ChangeGroupManagerNotRegistered {
            get {
                return ResourceManager.GetString("ChangeGroupManagerNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changeset Id must be a non-negative value.
        /// </summary>
        public static string ChangesetIdNonNegative {
            get {
                return ResourceManager.GetString("ChangesetIdNonNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IgnoreUnmappedPath.
        /// </summary>
        public static string CommandSwitchIgnoreUnmappedPath {
            get {
                return ResourceManager.GetString("CommandSwitchIgnoreUnmappedPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This conflict is detected when a migration action that attempts to create a file property fails.
        /// </summary>
        public static string Conflict_FilePropertyCreation_Description {
            get {
                return ResourceManager.GetString("Conflict_FilePropertyCreation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File property creation conflict type.
        /// </summary>
        public static string Conflict_FilePropertyCreation_Name {
            get {
                return ResourceManager.GetString("Conflict_FilePropertyCreation_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolve file property creation conflict by retrying the creation of the file property.
        /// </summary>
        public static string Conflict_FilePropertyCreation_RetryAction {
            get {
                return ResourceManager.GetString("Conflict_FilePropertyCreation_RetryAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolve file property creation conflict by skipping the creation of the file property.
        /// </summary>
        public static string Conflict_FilePropertyCreation_SkipAction {
            get {
                return ResourceManager.GetString("Conflict_FilePropertyCreation_SkipAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This conflict is detected when a migration action that attempts to create a label fails.
        /// </summary>
        public static string Conflict_LabelCreation_Description {
            get {
                return ResourceManager.GetString("Conflict_LabelCreation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label creation conflict type.
        /// </summary>
        public static string Conflict_LabelCreation_Name {
            get {
                return ResourceManager.GetString("Conflict_LabelCreation_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolve label creation conflict by retrying the creation of the label.
        /// </summary>
        public static string Conflict_LabelCreation_RetryAction {
            get {
                return ResourceManager.GetString("Conflict_LabelCreation_RetryAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolve label creation conflict by skipping the creation of the label.
        /// </summary>
        public static string Conflict_LabelCreation_SkipAction {
            get {
                return ResourceManager.GetString("Conflict_LabelCreation_SkipAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolve the &quot;Unmapped Work Item Type&quot; conflicts by skipping the migration of this type of Work Items..
        /// </summary>
        public static string Conflict_UnmappedWIT_Action_SkipMigration {
            get {
                return ResourceManager.GetString("Conflict_UnmappedWIT_Action_SkipMigration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This conflict is detected when a source Work Item Type is not mapped in the configuration..
        /// </summary>
        public static string Conflict_UnmappedWIT_Description {
            get {
                return ResourceManager.GetString("Conflict_UnmappedWIT_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Item Type &apos;{0}&apos; is not mapped in the configuration..
        /// </summary>
        public static string Conflict_UnmappedWIT_Details {
            get {
                return ResourceManager.GetString("Conflict_UnmappedWIT_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WIT unmapped Work Item Type conflict type.
        /// </summary>
        public static string Conflict_UnmappedWIT_Name {
            get {
                return ResourceManager.GetString("Conflict_UnmappedWIT_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflict Type (Reference Name: &apos;{0}&apos;) is not registered with the conflict maanger (ScopeId: &apos;{1}&apos;; SourceId: &apos;{2}&apos;)..
        /// </summary>
        public static string ConflictTypeNotRegistered {
            get {
                return ResourceManager.GetString("ConflictTypeNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified migration event..
        /// </summary>
        public static string DefaultEventString {
            get {
                return ResourceManager.GetString("DefaultEventString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The migration engine is unable to resolve a change conflict..
        /// </summary>
        public static string DefaultUnresolvableConflictExceptionMessage {
            get {
                return ResourceManager.GetString("DefaultUnresolvableConflictExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified version control migration event..
        /// </summary>
        public static string DefaultVCEventString {
            get {
                return ResourceManager.GetString("DefaultVCEventString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A provider dependency could not be resolved.  Provider not found: {0}..
        /// </summary>
        public static string DependentProviderMissing {
            get {
                return ResourceManager.GetString("DependentProviderMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session cannot be aborted because it is neither running nor paused..
        /// </summary>
        public static string ErrorAbortingSession {
            get {
                return ResourceManager.GetString("ErrorAbortingSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artifact Type {0} is not supported by the link provider..
        /// </summary>
        public static string ErrorArtifactTypeNotSupported {
            get {
                return ResourceManager.GetString("ErrorArtifactTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addin &apos;{0}&apos; threw exception: {1}.
        /// </summary>
        public static string ErrorCallingAddin {
            get {
                return ResourceManager.GetString("ErrorCallingAddin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The certificate identity specified in the WCF service configuration cannot be loaded..
        /// </summary>
        public static string ErrorCannotLoadCertificateIdentity {
            get {
                return ResourceManager.GetString("ErrorCannotLoadCertificateIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session cannot be completed because it is not running..
        /// </summary>
        public static string ErrorCompletingSession {
            get {
                return ResourceManager.GetString("ErrorCompletingSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider could not instantiate a linking engine object..
        /// </summary>
        public static string ErrorCreateLinkingEngine {
            get {
                return ResourceManager.GetString("ErrorCreateLinkingEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating migration provider factory instance from configuration xml..
        /// </summary>
        public static string ErrorCreatingProviderFromXml {
            get {
                return ResourceManager.GetString("ErrorCreatingProviderFromXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete Session Group &apos;{0}&apos; - it is still running..
        /// </summary>
        public static string ErrorDeletingActiveSessionGroup {
            get {
                return ResourceManager.GetString("ErrorDeletingActiveSessionGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save conflict resolution rule {0}. Another rule with the same reference name has already been created..
        /// </summary>
        public static string ErrorDuplicateResolutionRule {
            get {
                return ResourceManager.GetString("ErrorDuplicateResolutionRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TFS Integration Platform Windows Event Log Source &apos;{0}&apos; cannot be found..
        /// </summary>
        public static string ErrorEventLogSourceNotFound {
            get {
                return ResourceManager.GetString("ErrorEventLogSourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while executing an embedded SQL resource.  The error details are: {0}.
        /// </summary>
        public static string ErrorExecutingNamedSQLResource {
            get {
                return ResourceManager.GetString("ErrorExecutingNamedSQLResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get work item..
        /// </summary>
        public static string ErrorGetWorkItem {
            get {
                return ResourceManager.GetString("ErrorGetWorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &apos;{0}&apos; is invalid..
        /// </summary>
        public static string ErrorInvalidArg {
            get {
                return ResourceManager.GetString("ErrorInvalidArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; does not correspond to a conflict in the backlog..
        /// </summary>
        public static string ErrorInvalidConflictInternalId {
            get {
                return ResourceManager.GetString("ErrorInvalidConflictInternalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflict type {0} (Reference name: {1}) for resolution rule {2} is not registered in conflict manager (ScopeId: {3}; SourceId: {4} ({5}))..
        /// </summary>
        public static string ErrorInvalidConflictResolutionRule {
            get {
                return ResourceManager.GetString("ErrorInvalidConflictResolutionRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution action {0} is not valid for conflict type {1} ({2})..
        /// </summary>
        public static string ErrorInvalidResolutionActionForConflictType {
            get {
                return ResourceManager.GetString("ErrorInvalidResolutionActionForConflictType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinkTopology is unknown..
        /// </summary>
        public static string ErrorLinkTopologyIsUnknown {
            get {
                return ResourceManager.GetString("ErrorLinkTopologyIsUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Type {0} is not supported by the link provider..
        /// </summary>
        public static string ErrorLinkTypeNotSupported {
            get {
                return ResourceManager.GetString("ErrorLinkTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The change action does not have a parent change group persisted in data store..
        /// </summary>
        public static string ErrorMissingParentChangeGroup {
            get {
                return ResourceManager.GetString("ErrorMissingParentChangeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the serializer for the conflict resolution rule {0} ({1})..
        /// </summary>
        public static string ErrorMissingResolutionRuleSerializer {
            get {
                return ResourceManager.GetString("ErrorMissingResolutionRuleSerializer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VCPathTranslationService is not available for migration source &apos;{0}&apos;..
        /// </summary>
        public static string ErrorMissingVCPathTranslationService {
            get {
                return ResourceManager.GetString("ErrorMissingVCPathTranslationService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one resolution rules with Reference Name {0} are present in the Tfs Migration Database..
        /// </summary>
        public static string ErrorMultiResolutionRuleOfSameRefName {
            get {
                return ResourceManager.GetString("ErrorMultiResolutionRuleOfSameRefName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: More than one session group configuration have the same unique Id..
        /// </summary>
        public static string ErrorMultiSessionGroupConfigWithSameId {
            get {
                return ResourceManager.GetString("ErrorMultiSessionGroupConfigWithSameId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the conflicted change action associated with the raised migration conflict..
        /// </summary>
        public static string ErrorNonexistConflictChangeAction {
            get {
                return ResourceManager.GetString("ErrorNonexistConflictChangeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No work item tracking session is specified in the linking engine..
        /// </summary>
        public static string ErrorNoWitSessionInLinking {
            get {
                return ResourceManager.GetString("ErrorNoWitSessionInLinking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to pause an inactive session.
        /// </summary>
        public static string ErrorPausingSession {
            get {
                return ResourceManager.GetString("ErrorPausingSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider not found for migration source: &apos;{0}&apos;. Please make sure that the provider assembly is deployed in the &apos;Plugins&apos; folder and all its requisite resources are accessible..
        /// </summary>
        public static string ErrorProviderNotFound {
            get {
                return ResourceManager.GetString("ErrorProviderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find resolution rule with Reference Name {0} in the Tfs Migration Database..
        /// </summary>
        public static string ErrorResolutionRuleNotFound {
            get {
                return ResourceManager.GetString("ErrorResolutionRuleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot start Session Group &apos;{0}&apos; - the session group has been deleted..
        /// </summary>
        public static string ErrorRestartDeletedSessionGroup {
            get {
                return ResourceManager.GetString("ErrorRestartDeletedSessionGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot restart Session Group &apos;{0}&apos; - the session group has completed the OneTime migration. Please consider change the WorkFlowType.Frequency to ContinuousManual, if you want to restart it..
        /// </summary>
        public static string ErrorRestartOneTimeCompleteSessionGroup {
            get {
                return ResourceManager.GetString("ErrorRestartOneTimeCompleteSessionGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session cannot be resumed because it is not running..
        /// </summary>
        public static string ErrorResumingSession {
            get {
                return ResourceManager.GetString("ErrorResumingSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save duplicate LinkAction with Internal Id ({0})..
        /// </summary>
        public static string ErrorSaveDuplicateLinkAction {
            get {
                return ResourceManager.GetString("ErrorSaveDuplicateLinkAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session is already running..
        /// </summary>
        public static string ErrorSessionAlreadyRunning {
            get {
                return ResourceManager.GetString("ErrorSessionAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session cannot be started because it is already running..
        /// </summary>
        public static string ErrorStartingSession {
            get {
                return ResourceManager.GetString("ErrorStartingSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format string configured for the format string composition rule in the User Id Lookup setting is not valid..
        /// </summary>
        public static string ErrorUserIdFormatStringCompositionRule_InvalidFormat {
            get {
                return ResourceManager.GetString("ErrorUserIdFormatStringCompositionRule_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deadlock.
        /// </summary>
        public static string ErrReport_Exception_Message_Deadlock {
            get {
                return ResourceManager.GetString("ErrReport_Exception_Message_Deadlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not enough space on the disk.
        /// </summary>
        public static string ErrReport_Exception_Message_NotEnoughSpaceOnDisk {
            get {
                return ResourceManager.GetString("ErrReport_Exception_Message_NotEnoughSpaceOnDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout expired.
        /// </summary>
        public static string ErrReport_Exception_Message_Timeout {
            get {
                return ResourceManager.GetString("ErrReport_Exception_Message_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A local workspace is required.
        /// </summary>
        public static string ErrReport_Exception_Message_WorkspaceIsRequired {
            get {
                return ResourceManager.GetString("ErrReport_Exception_Message_WorkspaceIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load event sink provider attribute..
        /// </summary>
        public static string EventProviderAttributeMissing {
            get {
                return ResourceManager.GetString("EventProviderAttributeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event sink provider does not exist: {0}.
        /// </summary>
        public static string EventProviderNotExist {
            get {
                return ResourceManager.GetString("EventProviderNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred while loading AnalysisAddins: {0}.
        /// </summary>
        public static string ExceptionLoadingAnalysisAddin {
            get {
                return ResourceManager.GetString("ExceptionLoadingAnalysisAddin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred while loading MigrationAddins:{0}.
        /// </summary>
        public static string ExceptionLoadingMigrationAddin {
            get {
                return ResourceManager.GetString("ExceptionLoadingMigrationAddin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected failure occurred while creating a new version control migration action row..
        /// </summary>
        public static string FailureCreatingNewActionRow {
            get {
                return ResourceManager.GetString("FailureCreatingNewActionRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The File element is missing or empty..
        /// </summary>
        public static string FileElementEmpty {
            get {
                return ResourceManager.GetString("FileElementEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetLastMigratedChangeName: Query on Endpoint {0} returned 0 rows.
        /// </summary>
        public static string GetLastMigratedChangeNameFoundNoRows {
            get {
                return ResourceManager.GetString("GetLastMigratedChangeNameFoundNoRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint.Poll: GetLastMigratedChangeName returned empty name for endpoint &apos;{0}&apos;; no data will be saved.
        /// </summary>
        public static string GetLastMigratedChangeNameReturnedEmpty {
            get {
                return ResourceManager.GetString("GetLastMigratedChangeNameReturnedEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add new actions to a locked change grouping.
        /// </summary>
        public static string GroupingError_Add {
            get {
                return ResourceManager.GetString("GroupingError_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change the grouping comment after being locked.
        /// </summary>
        public static string GroupingError_Comment {
            get {
                return ResourceManager.GetString("GroupingError_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change the grouping ContainsBackloggedAction after being locked.
        /// </summary>
        public static string GroupingError_ContainsBackloggedAction {
            get {
                return ResourceManager.GetString("GroupingError_ContainsBackloggedAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change the grouping name after being locked.
        /// </summary>
        public static string GroupingError_Name {
            get {
                return ResourceManager.GetString("GroupingError_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change the grouping execution order after being locked.
        /// </summary>
        public static string GroupingError_Order {
            get {
                return ResourceManager.GetString("GroupingError_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change the grouping owner after being locked.
        /// </summary>
        public static string GroupingError_Owner {
            get {
                return ResourceManager.GetString("GroupingError_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change the grouping revision time after being locked.
        /// </summary>
        public static string GroupingError_RevisionTime {
            get {
                return ResourceManager.GetString("GroupingError_RevisionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change the grouping session ID after being locked.
        /// </summary>
        public static string GroupingError_SessionId {
            get {
                return ResourceManager.GetString("GroupingError_SessionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change the grouping source Id after being locked.
        /// </summary>
        public static string GroupingError_SourceId {
            get {
                return ResourceManager.GetString("GroupingError_SourceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change the grouping time after being locked.
        /// </summary>
        public static string GroupingError_Time {
            get {
                return ResourceManager.GetString("GroupingError_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflict description is invalid..
        /// </summary>
        public static string InvalidConflictDescription {
            get {
                return ResourceManager.GetString("InvalidConflictDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action with reference name &apos;{0}&apos; is not a valid resolution action for conflict type &apos;{1}&apos;..
        /// </summary>
        public static string InvalidConflictResolutionAction {
            get {
                return ResourceManager.GetString("InvalidConflictResolutionAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid conversion history information is provided. .
        /// </summary>
        public static string InvalidConversionHistoryInfo {
            get {
                return ResourceManager.GetString("InvalidConversionHistoryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description of the Change Action (Id: {0}) is not valid..
        /// </summary>
        public static string InvalideChangeActionDescription {
            get {
                return ResourceManager.GetString("InvalideChangeActionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid MD5 hash code.
        /// </summary>
        public static string InvalidMD5HashCode {
            get {
                return ResourceManager.GetString("InvalidMD5HashCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: &apos;{0}&apos; is not an integer value expected by this scope syntax..
        /// </summary>
        public static string InvalidScopeIntValueExpected {
            get {
                return ResourceManager.GetString("InvalidScopeIntValueExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Item is not an IMigrationFileAttachment for attachment operation.
        /// </summary>
        public static string InvalidSourceItemForAttachmentOperation {
            get {
                return ResourceManager.GetString("InvalidSourceItemForAttachmentOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a well-formed &quot;Details&quot; for VCContentConflict..
        /// </summary>
        public static string InvalidVCContentConflictDetailsString {
            get {
                return ResourceManager.GetString("InvalidVCContentConflictDetailsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a well-formed &quot;Details&quot; for WITEditEditConflict..
        /// </summary>
        public static string InvalidWitEditEditConflictDetailsString {
            get {
                return ResourceManager.GetString("InvalidWitEditEditConflictDetailsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastMigratedItemName: {0}.
        /// </summary>
        public static string LastMigratedItemName {
            get {
                return ResourceManager.GetString("LastMigratedItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded AnalysisAddin of type {0} for migration source &apos;{1}&apos;.
        /// </summary>
        public static string LoadedAnalysisAddin {
            get {
                return ResourceManager.GetString("LoadedAnalysisAddin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded MigrationAddin of type {0} for migration source &apos;{1}&apos;.
        /// </summary>
        public static string LoadedMigrationAddin {
            get {
                return ResourceManager.GetString("LoadedMigrationAddin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find mapped path for {0}.
        /// </summary>
        public static string MappingPathNotFound {
            get {
                return ResourceManager.GetString("MappingPathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MigrationAddin.
        /// </summary>
        public static string MigrationAddinKeyName {
            get {
                return ResourceManager.GetString("MigrationAddinKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did not find MigrationAddin with ID &apos;{0}&apos;.
        /// </summary>
        public static string MigrationAddinNotFound {
            get {
                return ResourceManager.GetString("MigrationAddinNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version control migration process has been aborted..
        /// </summary>
        public static string MigrationProcessAborted {
            get {
                return ResourceManager.GetString("MigrationProcessAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArtifactType display name cannot be empty..
        /// </summary>
        public static string MissingArtifactTypeDispName {
            get {
                return ResourceManager.GetString("MissingArtifactTypeDispName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArtifactType reference name cannot be empty..
        /// </summary>
        public static string MissingArtifactTypeRefName {
            get {
                return ResourceManager.GetString("MissingArtifactTypeRefName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the link&apos;s source artifact id (Uri: {0})..
        /// </summary>
        public static string MissingSourceLinkArtifact {
            get {
                return ResourceManager.GetString("MissingSourceLinkArtifact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to abort a non-started session.
        /// </summary>
        public static string NoAbortNonStarted {
            get {
                return ResourceManager.GetString("NoAbortNonStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot complete an aborted session..
        /// </summary>
        public static string NoCompleteAbortedException {
            get {
                return ResourceManager.GetString("NoCompleteAbortedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot register more than one session to TextReport.
        /// </summary>
        public static string OneSessionPerTextReport {
            get {
                return ResourceManager.GetString("OneSessionPerTextReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polling endpoint for migration source: {0}.
        /// </summary>
        public static string PollingEndpoint {
            get {
                return ResourceManager.GetString("PollingEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provider does not implement the ISyncMonitor interface:{0}.
        /// </summary>
        public static string ProviderDoesNotImplementISyncMonitor {
            get {
                return ResourceManager.GetString("ProviderDoesNotImplementISyncMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No provider handler is loaded for the Migration Souce: {0}.
        /// </summary>
        public static string ProviderHandlerNotLoadedForMigrationSouce {
            get {
                return ResourceManager.GetString("ProviderHandlerNotLoadedForMigrationSouce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflict resolution rule &apos;{0}&apos; is not applicable to the conflict of internal ID &apos;{1}&apos;..
        /// </summary>
        public static string ResolutionRuleNotApplicable {
            get {
                return ResourceManager.GetString("ResolutionRuleNotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scope is valid..
        /// </summary>
        public static string ScopeIsValid {
            get {
                return ResourceManager.GetString("ScopeIsValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session has been aborted..
        /// </summary>
        public static string SessionAborted {
            get {
                return ResourceManager.GetString("SessionAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to start an already started session..
        /// </summary>
        public static string SessionAlreadyStarted {
            get {
                return ResourceManager.GetString("SessionAlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session complete.
        /// </summary>
        public static string SessionComplete {
            get {
                return ResourceManager.GetString("SessionComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No session group found with ID: {0}.
        /// </summary>
        public static string SessionGroupNotFound {
            get {
                return ResourceManager.GetString("SessionGroupNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session with the Id &apos;{0}&apos; for the migration source &apos;{1}&apos; was not found.
        /// </summary>
        public static string SessionNotFoundForMigrationSource {
            get {
                return ResourceManager.GetString("SessionNotFoundForMigrationSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session has been paused..
        /// </summary>
        public static string SessionPaused {
            get {
                return ResourceManager.GetString("SessionPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session has been resumed..
        /// </summary>
        public static string SessionResumed {
            get {
                return ResourceManager.GetString("SessionResumed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting session..
        /// </summary>
        public static string SessionStarting {
            get {
                return ResourceManager.GetString("SessionStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session {0} references an undefined TFS server {1}..
        /// </summary>
        public static string SessionUsesUndefTfs {
            get {
                return ResourceManager.GetString("SessionUsesUndefTfs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The setting {0} was defined more than once in the same scope..
        /// </summary>
        public static string SettingDefinedTwice {
            get {
                return ResourceManager.GetString("SettingDefinedTwice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The setting {0} was not found..
        /// </summary>
        public static string SettingNotFound {
            get {
                return ResourceManager.GetString("SettingNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The migration DB does not have a valid extended property of &apos;ReferenceName&apos;. DB schema validation failed..
        /// </summary>
        public static string SQLInvalidDBReferenceName {
            get {
                return ResourceManager.GetString("SQLInvalidDBReferenceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The database schema (Reference Name: &apos;{0}&apos;) is not supported by the current version (v {1}) of the framework..
        /// </summary>
        public static string SQLMismatchingDBSchema {
            get {
                return ResourceManager.GetString("SQLMismatchingDBSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SQL configuration is missing the ConnectionString element.  The configuration must either define the Server and Database settings or the ConnectionString setting..
        /// </summary>
        public static string SQLMissingConnectionString {
            get {
                return ResourceManager.GetString("SQLMissingConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to the reporting SQL server using the specified connection string..
        /// </summary>
        public static string SQLReportConnectionStringNotValid {
            get {
                return ResourceManager.GetString("SQLReportConnectionStringNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SQL report provider configuration is missing the Database element.  The SQL report adaptor must either define the Server and Database settings or the ConnectionString setting..
        /// </summary>
        public static string SQLReportMissingDatabase {
            get {
                return ResourceManager.GetString("SQLReportMissingDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SQL report provider configuration is missing the Server attribute.  The SQL report adaptor must either define the Server and Database settings or the ConnectionString setting..
        /// </summary>
        public static string SQLReportMissingServer {
            get {
                return ResourceManager.GetString("SQLReportMissingServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully polled endpoint for migration source: {0}; Latency: {1}, BacklogCount: {2}.
        /// </summary>
        public static string SuccessfullyPolledEndpoint {
            get {
                return ResourceManager.GetString("SuccessfullyPolledEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collecting backlog data for {0} migration sources from {1} sessions.
        /// </summary>
        public static string SyncMonitorCollectingBacklogData {
            get {
                return ResourceManager.GetString("SyncMonitorCollectingBacklogData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncMonitor: ERROR: {0}.
        /// </summary>
        public static string SyncMonitorError {
            get {
                return ResourceManager.GetString("SyncMonitorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncMonitor: INFO: {0}.
        /// </summary>
        public static string SyncMonitorInfo {
            get {
                return ResourceManager.GetString("SyncMonitorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no active migration sessions.
        /// </summary>
        public static string SyncMonitorNoActiveSessions {
            get {
                return ResourceManager.GetString("SyncMonitorNoActiveSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not storing invalid latency data from adapter for migration source: {0}. LastMigratedChangeName: {1}.
        /// </summary>
        public static string SyncMonitorNotStoringInvalidLatencyPollData {
            get {
                return ResourceManager.GetString("SyncMonitorNotStoringInvalidLatencyPollData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Monitor Thread.
        /// </summary>
        public static string SyncMonitorThreadName {
            get {
                return ResourceManager.GetString("SyncMonitorThreadName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncMonitor: WARNING: {0}.
        /// </summary>
        public static string SyncMonitorWarning {
            get {
                return ResourceManager.GetString("SyncMonitorWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time for GetLastMigratedChangeName(): {0} ms.
        /// </summary>
        public static string TimeForGetLastMigratedChangeName {
            get {
                return ResourceManager.GetString("TimeForGetLastMigratedChangeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time for GetSummaryOfChangesSince(): {0} ms.
        /// </summary>
        public static string TimeForGetSummaryOfChangesSince {
            get {
                return ResourceManager.GetString("TimeForGetSummaryOfChangesSince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while querying for the next version control change grouping.  One change group was expected but multiple groups were returned..
        /// </summary>
        public static string TooManyChangeGroupsReturned {
            get {
                return ResourceManager.GetString("TooManyChangeGroupsReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two providers using the same name: {0}.
        /// </summary>
        public static string TwoProvidersOneName {
            get {
                return ResourceManager.GetString("TwoProvidersOneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There can only be one migration target named {0}.
        /// </summary>
        public static string TwoTargetsOneName {
            get {
                return ResourceManager.GetString("TwoTargetsOneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to Team Foundation Server.
        /// </summary>
        public static string UICredProvider_MessageText {
            get {
                return ResourceManager.GetString("UICredProvider_MessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to {0}.
        /// </summary>
        public static string UICredProvider_TitleText {
            get {
                return ResourceManager.GetString("UICredProvider_TitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load type: {0}.
        /// </summary>
        public static string UnableToLoadType {
            get {
                return ResourceManager.GetString("UnableToLoadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The high water mark {0}  is not registered with any session or source system. .
        /// </summary>
        public static string UninitializedHighWaterMark {
            get {
                return ResourceManager.GetString("UninitializedHighWaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The change action with Id {0} is not registered with the provider of type {1}..
        /// </summary>
        public static string UnknownChangeAction {
            get {
                return ResourceManager.GetString("UnknownChangeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown ChangeStatus value &quot;{0}&quot; was encountered..
        /// </summary>
        public static string UnknownChangeStatusValue {
            get {
                return ResourceManager.GetString("UnknownChangeStatusValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string UnknownEndpointSystem {
            get {
                return ResourceManager.GetString("UnknownEndpointSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred while loading the migration configuration.  {0}.
        /// </summary>
        public static string UnknownInitError {
            get {
                return ResourceManager.GetString("UnknownInitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while processing links..
        /// </summary>
        public static string UnknownLinkingException {
            get {
                return ResourceManager.GetString("UnknownLinkingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown migration target {0}.
        /// </summary>
        public static string UnknownMigrationTarget {
            get {
                return ResourceManager.GetString("UnknownMigrationTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string UnknownSource {
            get {
                return ResourceManager.GetString("UnknownSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown sourceId {0} is encountered. .
        /// </summary>
        public static string UnknownSourceId {
            get {
                return ResourceManager.GetString("UnknownSourceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user &apos;{0}&apos; that runs work item migration is not a member of Service Accounts Group on server &apos;{1}&apos;..
        /// </summary>
        public static string UserNotInServiceAccountGroup {
            get {
                return ResourceManager.GetString("UserNotInServiceAccountGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No version control mapping was found for the unknown server item..
        /// </summary>
        public static string VCMappingMissingUnknownItem {
            get {
                return ResourceManager.GetString("VCMappingMissingUnknownItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; - path is not mapped..
        /// </summary>
        public static string VCPathTranslationError_CannotFindFilterString {
            get {
                return ResourceManager.GetString("VCPathTranslationError_CannotFindFilterString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid canonical server path..
        /// </summary>
        public static string VCPathTranslationErrVCPathTranslationError_InvalidCanonicalPath {
            get {
                return ResourceManager.GetString("VCPathTranslationErrVCPathTranslationError_InvalidCanonicalPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisableTargetAnalysis.
        /// </summary>
        public static string VCSetting_DisableTargetAnalysis {
            get {
                return ResourceManager.GetString("VCSetting_DisableTargetAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} from &apos;{1}&apos; Id: {2};{3}{4}.
        /// </summary>
        public static string VerbosePlatformCommentSuffixFormat {
            get {
                return ResourceManager.GetString("VerbosePlatformCommentSuffixFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignoring difference between work items {0} on &apos;{1}&apos; and {2} on &apos;{3}&apos; because the first work item has been changed since the last sync.
        /// </summary>
        public static string WitDiffIngoringDiff1 {
            get {
                return ResourceManager.GetString("WitDiffIngoringDiff1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignoring difference between work items {0} on &apos;{1}&apos; and {2} on &apos;{3}&apos; because the second work item has been changed since the last sync.
        /// </summary>
        public static string WitDiffIngoringDiff2 {
            get {
                return ResourceManager.GetString("WitDiffIngoringDiff2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only checking for existence of corresponding work items; skipping content comparison.
        /// </summary>
        public static string WitDiffNoContentComparison {
            get {
                return ResourceManager.GetString("WitDiffNoContentComparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference Report.
        /// </summary>
        public static string WitDiffResultReportHeader {
            get {
                return ResourceManager.GetString("WitDiffResultReportHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----------------.
        /// </summary>
        public static string WitDiffResultReportSeparator {
            get {
                return ResourceManager.GetString("WitDiffResultReportSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source attachment &apos;{0}&apos; property &apos;{1}:&apos; First value: &apos;{2}&apos; Second value: &apos;{3}&apos;.
        /// </summary>
        public static string WitDiffResultWorkItemAttachmentDiffDetail {
            get {
                return ResourceManager.GetString("WitDiffResultWorkItemAttachmentDiffDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment differences:.
        /// </summary>
        public static string WitDiffResultWorkItemAttachmentDiffHeader {
            get {
                return ResourceManager.GetString("WitDiffResultWorkItemAttachmentDiffHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment name: {0}.
        /// </summary>
        public static string WitDiffResultWorkItemAttachmentMissingDetail {
            get {
                return ResourceManager.GetString("WitDiffResultWorkItemAttachmentMissingDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments found only one one side:.
        /// </summary>
        public static string WitDiffResultWorkItemAttachmentMissingHeader {
            get {
                return ResourceManager.GetString("WitDiffResultWorkItemAttachmentMissingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing errors:.
        /// </summary>
        public static string WitDiffResultWorkItemErrorsHeader {
            get {
                return ResourceManager.GetString("WitDiffResultWorkItemErrorsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field name: &apos;{0}&apos; First value: &apos;{1}&apos; Second value: &apos;{2}&apos;.
        /// </summary>
        public static string WitDiffResultWorkItemFieldDiffDetail {
            get {
                return ResourceManager.GetString("WitDiffResultWorkItemFieldDiffDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field differences:.
        /// </summary>
        public static string WitDiffResultWorkItemFieldDiffHeader {
            get {
                return ResourceManager.GetString("WitDiffResultWorkItemFieldDiffHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field name: &apos;{0}&apos; found only on &apos;{1}&apos;.
        /// </summary>
        public static string WitDiffResultWorkItemFieldMissing {
            get {
                return ResourceManager.GetString("WitDiffResultWorkItemFieldMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields found in work item description for one side but not the other:.
        /// </summary>
        public static string WitDiffResultWorkItemFieldMissingHeader {
            get {
                return ResourceManager.GetString("WitDiffResultWorkItemFieldMissingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Property &apos;{0}&apos;: First value: &apos;{1}&apos; Second value: &apos;{2}&apos;.
        /// </summary>
        public static string WitDiffResultWorkItemLinkDiffDetail {
            get {
                return ResourceManager.GetString("WitDiffResultWorkItemLinkDiffDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link differences:.
        /// </summary>
        public static string WitDiffResultWorkItemLinkDiffHeader {
            get {
                return ResourceManager.GetString("WitDiffResultWorkItemLinkDiffHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linked artifact and type: {0}.
        /// </summary>
        public static string WitDiffResultWorkItemLinkMissingDetail {
            get {
                return ResourceManager.GetString("WitDiffResultWorkItemLinkMissingDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links found only one one side:.
        /// </summary>
        public static string WitDiffResultWorkItemLinkMissingHeader {
            get {
                return ResourceManager.GetString("WitDiffResultWorkItemLinkMissingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work item {0} on &apos;{1}&apos; does not match work item {2} on &apos;{3}&apos;: {4}.
        /// </summary>
        public static string WitDiffResultWorkItemMismatch {
            get {
                return ResourceManager.GetString("WitDiffResultWorkItemMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown or non-existant work item id.
        /// </summary>
        public static string WitDiffUnknownWorkItemId {
            get {
                return ResourceManager.GetString("WitDiffUnknownWorkItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XML document describing work item {0} for &apos;{1}&apos; is missing child nodes for element {2}.
        /// </summary>
        public static string WitDiffWorkItemDescriptionMissingChildNodes {
            get {
                return ResourceManager.GetString("WitDiffWorkItemDescriptionMissingChildNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work item {0} on &apos;{1}&apos; matches work item {2} on &apos;{3}&apos;.
        /// </summary>
        public static string WitDiffWorkItemsMatch {
            get {
                return ResourceManager.GetString("WitDiffWorkItemsMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to update action row - expected 1 row, actually got {0}.
        /// </summary>
        public static string WrongRowCountUpdatingActions {
            get {
                return ResourceManager.GetString("WrongRowCountUpdatingActions", resourceCulture);
            }
        }
    }
}
