//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.TeamFoundation.Migration.Shell.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.TeamFoundation.Migration.Shell.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new rule.
        /// </summary>
        public static string AddNewRuleButtonTooltip {
            get {
                return ResourceManager.GetString("AddNewRuleButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelString {
            get {
                return ResourceManager.GetString("CancelString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Error.
        /// </summary>
        public static string CannotStopCaption {
            get {
                return ResourceManager.GetString("CannotStopCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The migration is in a transient state and cannot be stopped right now. Please try again..
        /// </summary>
        public static string CannotStopError {
            get {
                return ResourceManager.GetString("CannotStopError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current session completed successfully..
        /// </summary>
        public static string ConfigurationSuccessString {
            get {
                return ResourceManager.GetString("ConfigurationSuccessString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to conflicts.
        /// </summary>
        public static string ConflictsString {
            get {
                return ResourceManager.GetString("ConflictsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflict Type:.
        /// </summary>
        public static string ConflictTypeLabel {
            get {
                return ResourceManager.GetString("ConflictTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflict Type.
        /// </summary>
        public static string ConflictTypeString {
            get {
                return ResourceManager.GetString("ConflictTypeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data fields:.
        /// </summary>
        public static string DataFieldsLabel {
            get {
                return ResourceManager.GetString("DataFieldsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string DescriptionLabel {
            get {
                return ResourceManager.GetString("DescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Rule.
        /// </summary>
        public static string EditRuleString {
            get {
                return ResourceManager.GetString("EditRuleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global ({0}).
        /// </summary>
        public static string GlobalConflictsTabHeaderString {
            get {
                return ResourceManager.GetString("GlobalConflictsTabHeaderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Refresh.
        /// </summary>
        public static string LastRefreshString {
            get {
                return ResourceManager.GetString("LastRefreshString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new rule.
        /// </summary>
        public static string NewRuleViewTitle {
            get {
                return ResourceManager.GetString("NewRuleViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OKString {
            get {
                return ResourceManager.GetString("OKString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflict.
        /// </summary>
        public static string OneConflictString {
            get {
                return ResourceManager.GetString("OneConflictString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pausing.
        /// </summary>
        public static string PausingString {
            get {
                return ResourceManager.GetString("PausingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the chosen scope of &quot;{0}&quot;, the following {1} conflict(s) of type &quot;{2}&quot; will be resolved..
        /// </summary>
        public static string PreviewDialogMessageString {
            get {
                return ResourceManager.GetString("PreviewDialogMessageString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove rule.
        /// </summary>
        public static string RemoveRuleString {
            get {
                return ResourceManager.GetString("RemoveRuleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution Action:.
        /// </summary>
        public static string ResolutionActionLabel {
            get {
                return ResourceManager.GetString("ResolutionActionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution Action.
        /// </summary>
        public static string ResolutionActionString {
            get {
                return ResourceManager.GetString("ResolutionActionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolve.
        /// </summary>
        public static string ResolveConflictString {
            get {
                return ResourceManager.GetString("ResolveConflictString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolve.
        /// </summary>
        public static string ResolveString {
            get {
                return ResourceManager.GetString("ResolveString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the chosen scope of &quot;{0}&quot;, the following {1} conflict(s) of type &quot;{2}&quot; have been resolved..
        /// </summary>
        public static string RulesDialogMessageString {
            get {
                return ResourceManager.GetString("RulesDialogMessageString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules.
        /// </summary>
        public static string RulesString {
            get {
                return ResourceManager.GetString("RulesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveString {
            get {
                return ResourceManager.GetString("SaveString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope:.
        /// </summary>
        public static string ScopeLabel {
            get {
                return ResourceManager.GetString("ScopeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope.
        /// </summary>
        public static string ScopeString {
            get {
                return ResourceManager.GetString("ScopeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        public static string SessionGroupComboBoxSelectionString {
            get {
                return ResourceManager.GetString("SessionGroupComboBoxSelectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Group:.
        /// </summary>
        public static string SessionGroupLabel {
            get {
                return ResourceManager.GetString("SessionGroupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TFS Integration.
        /// </summary>
        public static string ShellHeaderString {
            get {
                return ResourceManager.GetString("ShellHeaderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source:.
        /// </summary>
        public static string SourceLabel {
            get {
                return ResourceManager.GetString("SourceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting.
        /// </summary>
        public static string StartingString {
            get {
                return ResourceManager.GetString("StartingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping.
        /// </summary>
        public static string StoppingString {
            get {
                return ResourceManager.GetString("StoppingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Control ({0}).
        /// </summary>
        public static string VCConflictsTabHeaderString {
            get {
                return ResourceManager.GetString("VCConflictsTabHeaderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Item Tracking ({0}).
        /// </summary>
        public static string WITConflictsTabHeaderString {
            get {
                return ResourceManager.GetString("WITConflictsTabHeaderString", resourceCulture);
            }
        }
    }
}
