//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.TeamFoundation.Migration.Shell.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ShellResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShellResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.TeamFoundation.Migration.Shell.Properties.ShellResources", typeof(ShellResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButtonString {
            get {
                return ResourceManager.GetString("CancelButtonString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program is released under the MS-PL license.  Please consult {0} for licensing details..
        /// </summary>
        public static string CopyrightWarningString {
            get {
                return ResourceManager.GetString("CopyrightWarningString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction of the migration (one-way or two-way).
        /// </summary>
        public static string DirectionTooltip {
            get {
                return ResourceManager.GetString("DirectionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Unhandled exception
        ///{0}.
        /// </summary>
        public static string ErrorDialogExceptionString {
            get {
                return ResourceManager.GetString("ErrorDialogExceptionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorDialogTitle {
            get {
                return ResourceManager.GetString("ErrorDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string ExportMenuItem {
            get {
                return ResourceManager.GetString("ExportMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How often the session runs:
        ///OneTime = session can only be run once to completion
        ///ContinuousManual = session can be re-run after completion
        ///ContinuousAutomatic = session will automatically re-run after completion.
        /// </summary>
        public static string FrequencyTooltip {
            get {
                return ResourceManager.GetString("FrequencyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string ImportMenuItem {
            get {
                return ResourceManager.GetString("ImportMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration Pipeline.
        /// </summary>
        public static string MigrationPipelineHeader {
            get {
                return ResourceManager.GetString("MigrationPipelineHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string OpenButtonString {
            get {
                return ResourceManager.GetString("OpenButtonString", resourceCulture);
            }
        }
        
        public static byte[] OpenFromDBImage {
            get {
                object obj = ResourceManager.GetObject("OpenFromDBImage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open from DB.
        /// </summary>
        public static string OpenFromDBString {
            get {
                return ResourceManager.GetString("OpenFromDBString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string OpenFromDBTitle {
            get {
                return ResourceManager.GetString("OpenFromDBTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File....
        /// </summary>
        public static string OpenFromFileString {
            get {
                return ResourceManager.GetString("OpenFromFileString", resourceCulture);
            }
        }
        
        public static byte[] PauseImage {
            get {
                object obj = ResourceManager.GetObject("PauseImage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] PlayImage {
            get {
                object obj = ResourceManager.GetObject("PlayImage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Providers.
        /// </summary>
        public static string ProvidersString {
            get {
                return ResourceManager.GetString("ProvidersString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButtonString {
            get {
                return ResourceManager.GetString("SaveButtonString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator:.
        /// </summary>
        public static string SaveToDBCreatorPrompt {
            get {
                return ResourceManager.GetString("SaveToDBCreatorPrompt", resourceCulture);
            }
        }
        
        public static byte[] SaveToDBImage {
            get {
                object obj = ResourceManager.GetObject("SaveToDBImage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Name:.
        /// </summary>
        public static string SaveToDBNamePrompt {
            get {
                return ResourceManager.GetString("SaveToDBNamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to DB.
        /// </summary>
        public static string SaveToDBString {
            get {
                return ResourceManager.GetString("SaveToDBString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveToDBTitle {
            get {
                return ResourceManager.GetString("SaveToDBTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Time.
        /// </summary>
        public static string SessionGroupCreationTimeColumn {
            get {
                return ResourceManager.GetString("SessionGroupCreationTimeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator.
        /// </summary>
        public static string SessionGroupCreatorColumn {
            get {
                return ResourceManager.GetString("SessionGroupCreatorColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SessionGroupNameColumn {
            get {
                return ResourceManager.GetString("SessionGroupNameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow.
        /// </summary>
        public static string SessionGroupWorkflowColumn {
            get {
                return ResourceManager.GetString("SessionGroupWorkflowColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Session.
        /// </summary>
        public static string SessionPauseTooltip {
            get {
                return ResourceManager.GetString("SessionPauseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Session.
        /// </summary>
        public static string SessionStartTooltip {
            get {
                return ResourceManager.GetString("SessionStartTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Session.
        /// </summary>
        public static string SessionStopTooltip {
            get {
                return ResourceManager.GetString("SessionStopTooltip", resourceCulture);
            }
        }
        
        public static byte[] StopImage {
            get {
                object obj = ResourceManager.GetObject("StopImage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must stop the current migration to edit current configuration. Do you want to stop the running session?.
        /// </summary>
        public static string StopSessionEditConfiguration {
            get {
                return ResourceManager.GetString("StopSessionEditConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must stop the current migration to open another session. Do you want to stop the running session?.
        /// </summary>
        public static string StopSessionExistingSession {
            get {
                return ResourceManager.GetString("StopSessionExistingSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must stop the current migration to create a new session. Do you want to stop the running session?.
        /// </summary>
        public static string StopSessionNewMigration {
            get {
                return ResourceManager.GetString("StopSessionNewMigration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Migration?.
        /// </summary>
        public static string StopSessionTitle {
            get {
                return ResourceManager.GetString("StopSessionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describes how to migrate context information.
        /// </summary>
        public static string SyncContextTooltip {
            get {
                return ResourceManager.GetString("SyncContextTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnknownProcess.
        /// </summary>
        public static string UnknownProcess {
            get {
                return ResourceManager.GetString("UnknownProcess", resourceCulture);
            }
        }
    }
}
