//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.TeamFoundation.Migration.Shell.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WpfViewResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WpfViewResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.TeamFoundation.Migration.Shell.Properties.WpfViewResources", typeof(WpfViewResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0}.
        /// </summary>
        public static string AboutApplicationString {
            get {
                return ResourceManager.GetString("AboutApplicationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutString {
            get {
                return ResourceManager.GetString("AboutString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        public static string ApplicationVersionString {
            get {
                return ResourceManager.GetString("ApplicationVersionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed {0}.
        /// </summary>
        public static string ClosedString {
            get {
                return ResourceManager.GetString("ClosedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseString {
            get {
                return ResourceManager.GetString("CloseString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing {0}....
        /// </summary>
        public static string ClosingString {
            get {
                return ResourceManager.GetString("ClosingString", resourceCulture);
            }
        }
        
        public static byte[] CopyImage {
            get {
                object obj = ResourceManager.GetObject("CopyImage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: This computer program is protected by copyright law and international treaties. Unauthorized reproduction or distribution of this program, or any portion of it, may result in severe civil and criminal penalties, and will be prosecuted to the maximum extent possible under the law..
        /// </summary>
        public static string CopyrightWarningString {
            get {
                return ResourceManager.GetString("CopyrightWarningString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string CopyString {
            get {
                return ResourceManager.GetString("CopyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created New Document.
        /// </summary>
        public static string CreatedNewDocString {
            get {
                return ResourceManager.GetString("CreatedNewDocString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture.
        /// </summary>
        public static string CultureString {
            get {
                return ResourceManager.GetString("CultureString", resourceCulture);
            }
        }
        
        public static byte[] CutImage {
            get {
                object obj = ResourceManager.GetObject("CutImage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string CutString {
            get {
                return ResourceManager.GetString("CutString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditString {
            get {
                return ResourceManager.GetString("EditString", resourceCulture);
            }
        }
        
        public static byte[] ErrorImage {
            get {
                object obj = ResourceManager.GetObject("ErrorImage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorString {
            get {
                return ResourceManager.GetString("ErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ExitString {
            get {
                return ResourceManager.GetString("ExitString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string FileString {
            get {
                return ResourceManager.GetString("FileString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string FindString {
            get {
                return ResourceManager.GetString("FindString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string HelpString {
            get {
                return ResourceManager.GetString("HelpString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexing complete.
        /// </summary>
        public static string IndexingCompleteString {
            get {
                return ResourceManager.GetString("IndexingCompleteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexing started....
        /// </summary>
        public static string IndexingStartedString {
            get {
                return ResourceManager.GetString("IndexingStartedString", resourceCulture);
            }
        }
        
        public static byte[] InfoImage {
            get {
                object obj = ResourceManager.GetObject("InfoImage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string InformationString {
            get {
                return ResourceManager.GetString("InformationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string MessageString {
            get {
                return ResourceManager.GetString("MessageString", resourceCulture);
            }
        }
        
        public static byte[] NewImage {
            get {
                object obj = ResourceManager.GetObject("NewImage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string NewString {
            get {
                return ResourceManager.GetString("NewString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OKString {
            get {
                return ResourceManager.GetString("OKString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened {0}.
        /// </summary>
        public static string OpenedString {
            get {
                return ResourceManager.GetString("OpenedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Error.
        /// </summary>
        public static string OpenErrorCaptionString {
            get {
                return ResourceManager.GetString("OpenErrorCaptionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open {0}.
        /// </summary>
        public static string OpenErrorMessageString {
            get {
                return ResourceManager.GetString("OpenErrorMessageString", resourceCulture);
            }
        }
        
        public static byte[] OpenImage {
            get {
                object obj = ResourceManager.GetObject("OpenImage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening {0}....
        /// </summary>
        public static string OpeningString {
            get {
                return ResourceManager.GetString("OpeningString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string OpenString {
            get {
                return ResourceManager.GetString("OpenString", resourceCulture);
            }
        }
        
        public static byte[] PasteImage {
            get {
                object obj = ResourceManager.GetObject("PasteImage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string PasteString {
            get {
                return ResourceManager.GetString("PasteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from recent files?.
        /// </summary>
        public static string QueryRemoveFromRecentCaptionString {
            get {
                return ResourceManager.GetString("QueryRemoveFromRecentCaptionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove {0} from the recent files list?.
        /// </summary>
        public static string QueryRemoveFromRecentMessageString {
            get {
                return ResourceManager.GetString("QueryRemoveFromRecentMessageString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes?.
        /// </summary>
        public static string QuerySaveCaptionString {
            get {
                return ResourceManager.GetString("QuerySaveCaptionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the current configuration changes to the database?.
        /// </summary>
        public static string QuerySaveConfigurationString {
            get {
                return ResourceManager.GetString("QuerySaveConfigurationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes?.
        /// </summary>
        public static string QuerySaveMessageString {
            get {
                return ResourceManager.GetString("QuerySaveMessageString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Files.
        /// </summary>
        public static string RecentFilesString {
            get {
                return ResourceManager.GetString("RecentFilesString", resourceCulture);
            }
        }
        
        public static byte[] RedoImage {
            get {
                object obj = ResourceManager.GetObject("RedoImage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string RedoString {
            get {
                return ResourceManager.GetString("RedoString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        public static string SaveAsString {
            get {
                return ResourceManager.GetString("SaveAsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved {0}.
        /// </summary>
        public static string SavedString {
            get {
                return ResourceManager.GetString("SavedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Error.
        /// </summary>
        public static string SaveErrorCaptionString {
            get {
                return ResourceManager.GetString("SaveErrorCaptionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save {0}.
        /// </summary>
        public static string SaveErrorMessageString {
            get {
                return ResourceManager.GetString("SaveErrorMessageString", resourceCulture);
            }
        }
        
        public static byte[] SaveImage {
            get {
                object obj = ResourceManager.GetObject("SaveImage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveString {
            get {
                return ResourceManager.GetString("SaveString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving {0}....
        /// </summary>
        public static string SavingString {
            get {
                return ResourceManager.GetString("SavingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search complete with {0} results.
        /// </summary>
        public static string SearchCompleteString {
            get {
                return ResourceManager.GetString("SearchCompleteString", resourceCulture);
            }
        }
        
        public static byte[] SearchImage {
            get {
                object obj = ResourceManager.GetObject("SearchImage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results.
        /// </summary>
        public static string SearchResultsString {
            get {
                return ResourceManager.GetString("SearchResultsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search started....
        /// </summary>
        public static string SearchStartedString {
            get {
                return ResourceManager.GetString("SearchStartedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skin.
        /// </summary>
        public static string SkinString {
            get {
                return ResourceManager.GetString("SkinString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string SourceString {
            get {
                return ResourceManager.GetString("SourceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click for status history....
        /// </summary>
        public static string StatusHistoryString {
            get {
                return ResourceManager.GetString("StatusHistoryString", resourceCulture);
            }
        }
        
        public static byte[] UndoImage {
            get {
                object obj = ResourceManager.GetObject("UndoImage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string UndoString {
            get {
                return ResourceManager.GetString("UndoString", resourceCulture);
            }
        }
        
        public static byte[] ValidateImage {
            get {
                object obj = ResourceManager.GetObject("ValidateImage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        public static string ValidateString {
            get {
                return ResourceManager.GetString("ValidateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation complete.
        /// </summary>
        public static string ValidationCompleteString {
            get {
                return ResourceManager.GetString("ValidationCompleteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Results.
        /// </summary>
        public static string ValidationResultsString {
            get {
                return ResourceManager.GetString("ValidationResultsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation started....
        /// </summary>
        public static string ValidationStartedString {
            get {
                return ResourceManager.GetString("ValidationStartedString", resourceCulture);
            }
        }
        
        public static byte[] WarningImage {
            get {
                object obj = ResourceManager.GetObject("WarningImage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string WarningString {
            get {
                return ResourceManager.GetString("WarningString", resourceCulture);
            }
        }
    }
}
