//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.TeamFoundation.Migration.Shell.Tfs2008ShellAdapter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.TeamFoundation.Migration.Shell.Tfs2008ShellAdapter.Properties.Resources" +
                            "", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This conflict is detected when an Area or Iteration Path exists on the server but should not..
        /// </summary>
        internal static string ExcessivePathConflictTypeDescription {
            get {
                return ResourceManager.GetString("ExcessivePathConflictTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excessive Path Conflict Type.
        /// </summary>
        internal static string ExcessivePathConflictTypeFriendlyName {
            get {
                return ResourceManager.GetString("ExcessivePathConflictTypeFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This conflict is detected when the size of an attachment file exceeds the maximum allowed attachment size on the TFS server..
        /// </summary>
        internal static string FileAttachmentOversizedConflictTypeDescription {
            get {
                return ResourceManager.GetString("FileAttachmentOversizedConflictTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TFS WIT attachment file oversized.
        /// </summary>
        internal static string FileAttachmentOversizedConflictTypeFriendlyName {
            get {
                return ResourceManager.GetString("FileAttachmentOversizedConflictTypeFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This conflict is detected when the migration service account does not met the permission requirements..
        /// </summary>
        internal static string InsufficientPermissionConflictTypeDescription {
            get {
                return ResourceManager.GetString("InsufficientPermissionConflictTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TFS WIT insufficient permission conflict type.
        /// </summary>
        internal static string InsufficientPermissionConflictTypeFriendlyName {
            get {
                return ResourceManager.GetString("InsufficientPermissionConflictTypeFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This conflict is detected when a TFS Work Item contains invalid field..
        /// </summary>
        internal static string InvalidFieldConflictTypeDescription {
            get {
                return ResourceManager.GetString("InvalidFieldConflictTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TFS WIT invalid field conflict type.
        /// </summary>
        internal static string InvalidFieldConflictTypeFriendlyName {
            get {
                return ResourceManager.GetString("InvalidFieldConflictTypeFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This conflict is detected when a TFS Work Item contains invalid field value.
        /// </summary>
        internal static string InvalidFieldValueConflictTypeDescription {
            get {
                return ResourceManager.GetString("InvalidFieldValueConflictTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TFS WIT invalid field value conflict type.
        /// </summary>
        internal static string InvalidFieldValueConflictTypeFriendlyName {
            get {
                return ResourceManager.GetString("InvalidFieldValueConflictTypeFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This conflict is detected when the change submitted to the TFS server is invalid..
        /// </summary>
        internal static string InvalidSubmissionConflictTypeDescription {
            get {
                return ResourceManager.GetString("InvalidSubmissionConflictTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TFS WIT invalid submission conflict type.
        /// </summary>
        internal static string InvalidSubmissionConflictTypeFriendlyName {
            get {
                return ResourceManager.GetString("InvalidSubmissionConflictTypeFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This conflict is detected when an unknown exception is thrown during Work Item data submission..
        /// </summary>
        internal static string WitGeneralConflictTypeDescription {
            get {
                return ResourceManager.GetString("WitGeneralConflictTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TFS WIT general conflict type.
        /// </summary>
        internal static string WitGeneralConflictTypeFriendlyName {
            get {
                return ResourceManager.GetString("WitGeneralConflictTypeFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This conflict is detected when the history information of migrated work item is not found..
        /// </summary>
        internal static string WorkItemHistoryNotFoundConflictTypeDescription {
            get {
                return ResourceManager.GetString("WorkItemHistoryNotFoundConflictTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TFS WIT history not found conflict type.
        /// </summary>
        internal static string WorkItemHistoryNotFoundConflictTypeFriendlyName {
            get {
                return ResourceManager.GetString("WorkItemHistoryNotFoundConflictTypeFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This conflict is detected when the Work Item Type of a Work Item does not exist on the target TFS system..
        /// </summary>
        internal static string WorkItemTypeNotExistConflictTypeDescription {
            get {
                return ResourceManager.GetString("WorkItemTypeNotExistConflictTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TFS Work Item Type not exist conflict type.
        /// </summary>
        internal static string WorkItemTypeNotExistConflictTypeFriendlyName {
            get {
                return ResourceManager.GetString("WorkItemTypeNotExistConflictTypeFriendlyName", resourceCulture);
            }
        }
    }
}
