//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.TeamFoundation.Migration.TfsFileSystemAdapter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TfsFileSystemResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TfsFileSystemResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.TeamFoundation.Migration.TfsFileSystemAdapter.TfsFileSystemResources", typeof(TfsFileSystemResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TfsFileSystemAdapter: Did not find Addin with ID &apos;{0}&apos;.
        /// </summary>
        internal static string AddinNotFound {
            get {
                return ResourceManager.GetString("AddinNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TfsFileSystemAdapter only supports migrating from file system to Tfs system..
        /// </summary>
        internal static string CannotMigrateToFileSystem {
            get {
                return ResourceManager.GetString("CannotMigrateToFileSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when trying to connect to the destination TFS server. {0}.
        /// </summary>
        internal static string ErrorConnectingTargetTfsServer {
            get {
                return ResourceManager.GetString("ErrorConnectingTargetTfsServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred getting items for diff from folder &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string GetDiffItemsException {
            get {
                return ResourceManager.GetString("GetDiffItemsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lastProcessedChangeItemId argument (&apos;{0}&apos;) is not in the correct format..
        /// </summary>
        internal static string InvalidChangeItemIdFormat {
            get {
                return ResourceManager.GetString("InvalidChangeItemIdFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TfsFileSystemAdapter: Loaded Addin of type {0}.
        /// </summary>
        internal static string LoadedAddin {
            get {
                return ResourceManager.GetString("LoadedAddin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TfsFileSystemAdapter: No changes ready to migrate.
        /// </summary>
        internal static string NoChangesReadyToMigrate {
            get {
                return ResourceManager.GetString("NoChangesReadyToMigrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TfsFileSystemAdapter: No PreAnalysisAddin found to indicate readiness to migrate; will migrate all files with different content.
        /// </summary>
        internal static string PreAnalysisAddinNotFound {
            get {
                return ResourceManager.GetString("PreAnalysisAddinNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TfsFileSystemAdapter: Unable to get HashValue for item {0}: {1}.
        /// </summary>
        internal static string UnableToGetHashVaue {
            get {
                return ResourceManager.GetString("UnableToGetHashVaue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TfsFileSystemAdapter: Updated HighWaterMark time to {0}.
        /// </summary>
        internal static string UpdatedHighWaterMark {
            get {
                return ResourceManager.GetString("UpdatedHighWaterMark", resourceCulture);
            }
        }
    }
}
